"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { AlertTriangle,BookOpen,CalendarCheck,CheckCircle2,ChevronRight,Circle,LayoutDashboard,LogOut,Sparkles,Target } from "lucide-react";
import type { Profile } from "@/components/auth/AuthProvider";
import type { CncLearningRecord } from "@/services/cnc-learning-records";
import { CNC_ASSESSMENT_PLAN,CNC_TOTAL_ASSESSMENTS,cncAssessmentProgress } from "@/services/cnc-progress";
import { fetchMyAttendance } from "@/services/course-attendance";
import { fetchOpenCncLessons } from "@/services/course-lesson-release";
import { fetchMyCncDrawingSubmissions,type CncDrawingSubmission } from "@/services/cnc-drawing-submissions";
import StudentAttendancePanel from "@/components/attendance/StudentAttendancePanel";
import StudentCompetencyCard from "@/components/competencies/StudentCompetencyCard";
import StudentFinalGradeCard from "@/components/dashboard/StudentFinalGradeCard";
import StudentCodeField from "@/components/dashboard/StudentCodeField";

type Enrollment={status:string;enrolled_at:string;course:{id:number;name:string;class_label:string;school_year:string;status:string}};
const lessonInfo=[{id:"lesson-1",group:"Chung",title:"Tổng quan máy CNC"},{id:"lesson-2",group:"Tiện CNC",title:"Lập trình tiện"},{id:"lesson-4-turn",group:"Tiện CNC",title:"Vận hành máy tiện"},{id:"lesson-5",group:"Tiện CNC",title:"Gia công tiện"},{id:"lesson-3",group:"Phay CNC",title:"Lập trình phay"},{id:"lesson-4-mill",group:"Phay CNC",title:"Vận hành máy phay"},{id:"lesson-6",group:"Phay CNC",title:"Gia công phay"}];
const labels:Record<string,string>={final:"Kiểm tra cuối bài","exercise-1":"Nhận biết","exercise-2":"Dịch block","exercise-3":"Điền khuyết","exercise-4":"Viết chương trình","exercise-5":"Mô phỏng","machine-operation":"Vận hành máy","tool-setup":"Cài đặt dao","checklist-practice":"Checklist tự luyện",checklist:"Checklist thực hành","rubric-exam":"Thi thực hành tổng hợp"};

export default function StudentLearningDashboard({profile,email,studentId,enrollment,records,onSignOut,preview=false}:{profile:Profile|null;email?:string;studentId:string;enrollment:Enrollment;records:CncLearningRecord[];onSignOut:()=>void;preview?:boolean}){const[tab,setTab]=useState<"overview"|"learning"|"scores"|"attendance">("overview");const progress=cncAssessmentProgress(records);const scored=records.filter(row=>row.total_questions&&row.best_score!==null);const accuracy=scored.length?Math.round(scored.reduce((sum,row)=>sum+100*(row.best_score??0)/(row.total_questions??1),0)/scored.length):0;const next=lessonInfo.find(item=>(CNC_ASSESSMENT_PLAN[item.id]??[]).some(id=>!records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)))??lessonInfo[0];
  const[attention,setAttention]=useState<{reasons:string[];rejected:CncDrawingSubmission[]}|null>(null);
  useEffect(()=>{let cancelled=false;Promise.all([fetchOpenCncLessons(enrollment.course.id).catch(()=>["lesson-1"]),fetchMyAttendance(enrollment.course.id,studentId).catch(()=>[]),fetchMyCncDrawingSubmissions(enrollment.course.id).catch(()=>[])]).then(([openLessons,attendance,submissions])=>{if(cancelled)return;const openedKeys=new Set(openLessons.flatMap(lessonId=>(CNC_ASSESSMENT_PLAN[lessonId]??[]).map(assessmentId=>`${lessonId}:${assessmentId}`)));const openedTotal=openedKeys.size;const inScope=records.filter(row=>openedKeys.has(`${row.lesson_id}:${row.assessment_id}`));const passed=inScope.filter(row=>row.completed).length;const pctOpen=openedTotal?Math.round(passed/openedTotal*100):0;const failed=inScope.filter(row=>row.attempt_count>=3&&!row.completed).length;const absent=attendance.filter(row=>row.status==="absent").length;const late=attendance.filter(row=>row.status==="late").length;const uneven=attendance.length>=3&&(absent+late)/attendance.length>=.3;const reasons=[openedTotal>0&&pctOpen<30?`Bài đã mở: ${passed}/${openedTotal} đạt · ${pctOpen}%`:"",failed?`${failed} bài đã mở chưa đạt sau ≥3 lần`:"",absent?`Vắng ${absent} buổi`:"",late?`Đi muộn ${late} lần`:"",uneven?"Đi học chưa đều":""].filter(Boolean);setAttention({reasons,rejected:submissions.filter(item=>item.status==="rejected")})}).catch(()=>{});return()=>{cancelled=true}},[enrollment.course.id,studentId,records]);
  return <div className="space-y-4 sm:space-y-6">
  <section className="relative overflow-hidden rounded-2xl border border-line bg-panel p-4 sm:rounded-3xl sm:p-8"><div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[12px] font-bold uppercase tracking-[.14em] text-primary sm:text-xs sm:tracking-[.16em]">{preview?"Chế độ xem thử · Học sinh":"Không gian học tập của tôi"}</p><h1 className="mt-1.5 truncate font-display text-2xl font-bold text-ink sm:mt-2 sm:text-3xl">Chào {profile?.full_name||"bạn"} 👋</h1><p className="mt-1.5 text-xs text-muted sm:mt-2 sm:text-sm">{profile?.class_name?`Lớp ${profile.class_name} · `:""}{enrollment.course.name} · {enrollment.course.school_year}</p>{email&&<p className="mt-1 hidden text-xs text-muted sm:block">{email}</p>}<StudentCodeField studentId={studentId} preview={preview}/></div><button onClick={onSignOut} aria-label={preview?"Quay lại Dashboard giáo viên":"Đăng xuất"} className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-line text-ink sm:h-auto sm:w-auto sm:gap-2 sm:px-4 sm:py-2 sm:text-sm sm:font-bold"><LogOut size={16}/><span className="hidden sm:inline">{preview?"Quay lại Dashboard giáo viên":"Đăng xuất"}</span></button></div><div className="relative mt-5 sm:mt-6"><div className="mb-2 flex items-end justify-between gap-3 text-xs"><b className="text-primary">Năng lượng học tập</b><span className="whitespace-nowrap font-mono text-[12px] text-muted sm:text-xs">{progress.passed}/{CNC_TOTAL_ASSESSMENTS} · {progress.pct}%</span></div><div className="h-3.5 overflow-hidden rounded-full border border-line bg-surface-2 sm:h-4"><div className="h-full rounded-full bg-primary" style={{width:`${progress.pct}%`}}/></div><StudentCompetencyCard courseId={enrollment.course.id} studentId={studentId} records={records}/></div></section>
  <nav className="sticky top-16 z-40 grid grid-cols-4 gap-1 rounded-2xl border border-line bg-panel-deep/95 p-1.5 backdrop-blur sm:top-20 sm:flex sm:gap-2 sm:overflow-x-auto sm:p-2">{([{id:"overview",label:"Tổng quan",icon:LayoutDashboard},{id:"learning",label:"Học tập",icon:BookOpen},{id:"scores",label:"Kết quả",icon:Target},{id:"attendance",label:"Điểm danh",icon:CalendarCheck}]as const).map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`inline-flex min-w-0 flex-col items-center justify-center gap-1 rounded-xl px-1 py-2 text-[12px] font-bold sm:shrink-0 sm:flex-row sm:gap-2 sm:px-4 sm:py-3 sm:text-sm ${tab===item.id?"bg-primary text-white":"text-muted hover:bg-surface-2"}`}><Icon size={17}/><span className="truncate">{item.label}</span></button>})}</nav>
  {tab==="overview"&&<>{attention&&(attention.reasons.length>0||attention.rejected.length>0)&&<section className="rounded-2xl border border-danger/30 bg-danger/5 p-4 sm:p-5"><div className="flex items-center gap-2"><AlertTriangle size={18} className="text-danger"/><h2 className="font-display text-base font-bold text-ink sm:text-lg">Cần chú ý</h2></div>{attention.reasons.length>0&&<ul className="mt-3 space-y-1.5 text-xs text-ink sm:text-sm">{attention.reasons.map((reason,index)=><li key={index} className="flex items-start gap-2"><span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-danger"/>{reason}</li>)}</ul>}{attention.rejected.length>0&&<div className="mt-3 space-y-2">{attention.rejected.map(item=>{const title=lessonInfo.find(lesson=>lesson.id===item.lesson_id)?.title??item.lesson_id;return <Link key={item.id} href={`/lop-hoc/cnc/?bai=${item.lesson_id}`} className="flex items-center justify-between gap-3 rounded-xl border border-line bg-panel p-3"><div className="min-w-0"><strong className="block truncate text-sm text-ink">Nộp lại: {title}</strong>{item.teacher_feedback&&<small className="mt-1 block truncate text-danger">{item.teacher_feedback}</small>}</div><ChevronRight size={16} className="shrink-0 text-danger"/></Link>})}</div>}</section>}<section className="grid grid-cols-3 gap-2 sm:gap-3"><Stat value={`${progress.pct}%`} label="Tiến độ"/><Stat value={scored.length?`${accuracy}%`:"—"} label="Chính xác"/><Stat value={`${progress.passed}/${CNC_TOTAL_ASSESSMENTS}`} label="Đã đạt"/></section><Link href={`/lop-hoc/cnc/?bai=${next.id}`} className="flex items-center justify-between gap-3 rounded-2xl border border-primary bg-primary p-4 text-white hover:bg-primary-dark sm:p-5"><div className="min-w-0"><small className="text-[12px] font-bold uppercase tracking-wider text-blue-100 sm:text-xs">Học tiếp theo</small><h2 className="mt-1 truncate font-display text-lg font-bold text-white sm:text-xl">{next.title}</h2><p className="mt-1 text-xs text-blue-100 sm:text-sm">Vào bài học hoặc làm bài kiểm tra tiếp theo.</p></div><ChevronRight className="shrink-0 text-blue-100"/></Link></>}
  {tab==="learning"&&<Learning records={records}/>} {tab==="scores"&&<><StudentFinalGradeCard courseId={enrollment.course.id} studentId={studentId} records={records}/><Scores records={records}/></>} {tab==="attendance"&&<StudentAttendancePanel courseId={enrollment.course.id} studentId={studentId}/>}<button className="fixed bottom-6 right-6 z-50 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-primary-dark"><Sparkles size={17}/>Hỏi AI học cùng</button></div>}

function Learning({records}:{records:CncLearningRecord[]}){return <div className="space-y-5">{["Chung","Tiện CNC","Phay CNC"].map(group=><section key={group} className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-display text-xl font-bold text-ink">{group}</h2><p className="mt-1 text-sm text-slate-500">Chọn nội dung để học tiếp, xem lại bài giảng hoặc hỏi trợ giảng AI.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{lessonInfo.filter(item=>item.group===group).map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const passed=plan.filter(id=>records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)).length;const started=records.some(row=>row.lesson_id===item.id);const completed=plan.length>0&&passed===plan.length;return <article key={item.id} className="rounded-xl border border-line bg-surface-2 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-ink">{item.title}</strong><span className={`rounded-full px-2.5 py-1 text-[12px] font-bold ${completed?"bg-ok/10 text-ok":started?"bg-primary-soft text-primary":"bg-surface-2 text-slate-500"}`}>{completed?"Đã hoàn thành":started?"Đang học":"Chưa bắt đầu"}</span></div><div className="mt-4 flex gap-2"><Link href={`/lop-hoc/cnc/?bai=${item.id}`} className="rounded-full bg-primary px-3 py-1.5 text-xs font-bold text-white">{completed?"Xem lại":"Học tiếp"}</Link><button className="rounded-full border border-line px-3 py-1.5 text-xs font-bold text-primary">Hỏi AI</button></div></article>})}</div></section>)}</div>}
function Scores({records}:{records:CncLearningRecord[]}){return <div className="space-y-3">{lessonInfo.map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const rows=plan.map(id=>({id,record:records.find(row=>row.lesson_id===item.id&&row.assessment_id===id)}));return <details key={item.id} open={rows.some(row=>row.record)} className="rounded-2xl border border-line bg-panel p-5"><summary className="cursor-pointer font-bold text-ink">{item.title} <span className="float-right text-xs text-primary">{rows.filter(row=>row.record?.completed).length}/{plan.length} đạt</span></summary><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map(({id,record})=>{const pct=record?.total_questions?Math.round(100*(record.best_score??0)/record.total_questions):0;const tone=record?.completed?"border-ok/25 bg-ok/5 hover:border-ok/50":record?.attempt_count&&record.attempt_count>=3?"border-danger/25 bg-danger/5 hover:border-danger/50":record?"border-warn/25 bg-warn/5 hover:border-warn/50":"border-line hover:border-line-strong";const bar=record?.completed?"bg-ok":record?.attempt_count&&record.attempt_count>=3?"bg-danger":"bg-warn";return <Link key={id} href={`/lop-hoc/cnc/?bai=${item.id}`} className={`group rounded-xl border p-3 transition hover:-translate-y-0.5 ${tone}`}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs text-muted">{record?.completed?<CheckCircle2 size={14} className="text-ok"/>:<Circle size={14} className="text-muted"/>}{labels[id]??id}</span><ChevronRight size={14} className="text-muted transition group-hover:translate-x-0.5 group-hover:text-ink"/></div><div className="mt-1 flex justify-between"><b className="text-ink">{record?`${record.best_score}/${record.total_questions}`:"Chưa làm"}</b>{record&&<span className="text-xs text-slate-500">{record.attempt_count} lần</span>}</div>{record&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface-2"><div className={`h-full rounded-full ${bar}`} style={{width:`${pct}%`}}/></div>}</Link>})}</div></details>})}</div>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-xl border border-line bg-surface-2 p-3 sm:rounded-2xl sm:p-5"><strong className="text-xl text-ink sm:text-3xl">{value}</strong><p className="mt-1 truncate text-[12px] font-bold uppercase tracking-wide text-muted sm:text-xs sm:tracking-wider">{label}</p></div>}
