"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { BookOpen,CalendarCheck,ChevronRight,LayoutDashboard,LogOut,Sparkles,Target,Trophy } from "lucide-react";
import type { Profile } from "@/components/auth/AuthProvider";
import type { CncLearningRecord } from "@/services/cnc-learning-records";
import { CNC_ASSESSMENT_PLAN,CNC_TOTAL_ASSESSMENTS,cncAssessmentProgress } from "@/services/cnc-progress";
import { fetchCncCourseLeaderboard,studentTitles } from "@/services/cnc-leaderboard";
import StudentAttendancePanel from "@/components/attendance/StudentAttendancePanel";
import StudentCompetencyCard from "@/components/competencies/StudentCompetencyCard";

type Enrollment={status:string;enrolled_at:string;course:{id:number;name:string;class_label:string;school_year:string;status:string}};
const lessonInfo=[{id:"lesson-1",group:"Chung",title:"An toàn lao động"},{id:"lesson-2",group:"Tiện CNC",title:"Lập trình tiện"},{id:"lesson-4-turn",group:"Tiện CNC",title:"Vận hành máy tiện"},{id:"lesson-5",group:"Tiện CNC",title:"Gia công tiện"},{id:"lesson-3",group:"Phay CNC",title:"Lập trình phay"},{id:"lesson-4-mill",group:"Phay CNC",title:"Vận hành máy phay"},{id:"lesson-6",group:"Phay CNC",title:"Gia công phay"}];
const labels:Record<string,string>={final:"Kiểm tra cuối bài","exercise-1":"Nhận biết","exercise-2":"Dịch block","exercise-3":"Điền khuyết","exercise-4":"Viết chương trình","exercise-5":"Mô phỏng","machine-operation":"Vận hành máy","tool-setup":"Cài đặt dao"};

export default function StudentLearningDashboard({profile,email,studentId,enrollment,records,onSignOut}:{profile:Profile|null;email?:string;studentId:string;enrollment:Enrollment;records:CncLearningRecord[];onSignOut:()=>void}){const[tab,setTab]=useState<"overview"|"learning"|"scores"|"attendance">("overview");const[titles,setTitles]=useState<ReturnType<typeof studentTitles>>([]);const progress=cncAssessmentProgress(records);const scored=records.filter(row=>row.total_questions&&row.best_score!==null);const accuracy=scored.length?Math.round(scored.reduce((sum,row)=>sum+100*(row.best_score??0)/(row.total_questions??1),0)/scored.length):0;useEffect(()=>{void fetchCncCourseLeaderboard(enrollment.course.id).then(rows=>setTitles(studentTitles(rows,studentId))).catch(()=>setTitles([]))},[enrollment.course.id,studentId]);const next=lessonInfo.find(item=>(CNC_ASSESSMENT_PLAN[item.id]??[]).some(id=>!records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)))??lessonInfo[0];return <div className="space-y-6">
  <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#172c46] via-[#0e1c32] to-[#071426] p-6 sm:p-8"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl"/><div className="relative flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-300">Không gian học tập của tôi</p><h1 className="mt-2 font-display text-3xl font-bold text-white">Chào {profile?.full_name||"bạn"} 👋</h1><p className="mt-2 text-sm text-slate-400">{profile?.class_name?`Lớp ${profile.class_name} · `:""}{enrollment.course.name} · {enrollment.course.school_year}</p><p className="mt-1 text-xs text-slate-600">{email}</p></div><button onClick={onSignOut} className="inline-flex h-fit items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-slate-300"><LogOut size={15}/>Đăng xuất</button></div><div className="relative mt-6"><div className="mb-2 flex justify-between text-xs"><b className="text-cyan-200">Thanh năng lượng học tập</b><span className="font-mono text-slate-400">{progress.passed}/{CNC_TOTAL_ASSESSMENTS} bài đạt · {progress.pct}%</span></div><div className="h-4 overflow-hidden rounded-full border border-white/10 bg-[#050914]"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 via-cyan-400 to-sky-300 shadow-[0_0_18px_rgba(56,189,248,.45)]" style={{width:`${progress.pct}%`}}/></div></div></section>
  <nav className="sticky top-20 z-40 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#080d1d]/95 p-2 backdrop-blur">{([{id:"overview",label:"Tổng quan",icon:LayoutDashboard},{id:"learning",label:"Học tập",icon:BookOpen},{id:"scores",label:"Điểm của tôi",icon:Target},{id:"attendance",label:"Điểm danh",icon:CalendarCheck}]as const).map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab===item.id?"bg-blue-600 text-white":"text-slate-400 hover:bg-white/5"}`}><Icon size={17}/>{item.label}</button>})}</nav>
  {tab==="overview"&&<><section className="grid gap-3 sm:grid-cols-3"><Stat value={`${progress.pct}%`} label="Tiến độ khóa"/><Stat value={scored.length?`${accuracy}%`:"—"} label="Độ chính xác"/><Stat value={`${progress.passed}/${CNC_TOTAL_ASSESSMENTS}`} label="Chốt đã vượt"/></section><Link href={`/lop-hoc/cnc/?bai=${next.id}`} className="flex items-center justify-between rounded-2xl border border-orange-400/20 bg-gradient-to-r from-orange-500/10 to-transparent p-5"><div><small className="font-bold uppercase tracking-wider text-orange-300">Kèo học tiếp theo</small><h2 className="mt-1 font-display text-xl font-bold text-white">{next.title}</h2><p className="text-sm text-slate-400">Vào bài học, làm kiểm tra hoặc xem lại kiến thức.</p></div><ChevronRight className="text-orange-300"/></Link><TitleShelf titles={titles}/><StudentCompetencyCard courseId={enrollment.course.id} studentId={studentId} records={records}/></>}
  {tab==="learning"&&<Learning records={records}/>} {tab==="scores"&&<Scores records={records}/>} {tab==="attendance"&&<StudentAttendancePanel courseId={enrollment.course.id} studentId={studentId}/>}<button className="fixed bottom-6 right-6 z-50 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-violet-600 to-blue-600 px-5 py-3 text-sm font-bold text-white shadow-2xl"><Sparkles size={17}/>Hỏi AI học cùng</button></div>}

function Learning({records}:{records:CncLearningRecord[]}){return <div className="space-y-5">{["Chung","Tiện CNC","Phay CNC"].map(group=><section key={group} className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><h2 className="font-display text-xl font-bold text-white">{group}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{lessonInfo.filter(item=>item.group===group).map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const passed=plan.filter(id=>records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)).length;return <article key={item.id} className="rounded-xl border border-white/5 bg-white/[.02] p-4"><div className="flex justify-between"><strong className="text-white">{item.title}</strong><b className="text-xs text-cyan-300">{passed}/{plan.length}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-blue-500 to-cyan-300" style={{width:`${plan.length?100*passed/plan.length:0}%`}}/></div><div className="mt-4 flex gap-2"><Link href={`/lop-hoc/cnc/?bai=${item.id}`} className="rounded-full bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">{passed?"Xem lại / học tiếp":"Vào bài học"}</Link><button className="rounded-full border border-violet-400/20 px-3 py-1.5 text-xs font-bold text-violet-200">Hỏi AI</button></div></article>})}</div></section>)}</div>}
function Scores({records}:{records:CncLearningRecord[]}){return <div className="space-y-3">{lessonInfo.map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const rows=plan.map(id=>({id,record:records.find(row=>row.lesson_id===item.id&&row.assessment_id===id)}));return <details key={item.id} open={rows.some(row=>row.record)} className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><summary className="cursor-pointer font-bold text-white">{item.title} <span className="float-right text-xs text-cyan-300">{rows.filter(row=>row.record?.completed).length}/{plan.length} đạt</span></summary><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map(({id,record})=><div key={id} className={`rounded-xl border p-3 ${record?.completed?"border-emerald-500/20 bg-emerald-500/5":record?.attempt_count&&record.attempt_count>=3?"border-red-500/20 bg-red-500/5":record?"border-amber-500/20 bg-amber-500/5":"border-white/5"}`}><small className="text-slate-400">{labels[id]??id}</small><div className="mt-1 flex justify-between"><b className="text-white">{record?`${record.best_score}/${record.total_questions}`:"Chưa làm"}</b>{record&&<span className="text-xs text-slate-500">{record.attempt_count} lần</span>}</div></div>)}</div></details>})}</div>}
function TitleShelf({titles}:{titles:ReturnType<typeof studentTitles>}){const items=titles.length?titles:[{id:"speedrunner",name:"Quiz Speedrunner",description:"Người mở điểm sớm nhất lớp",earned:false,icon:"⚡"},{id:"fast-finish",name:"Về đích tốc độ ánh sáng",description:"Hoàn thành khóa sớm nhất lớp",earned:false,icon:"🚀"},{id:"accuracy",name:"Aim chuẩn khỏi chỉnh",description:"Độ chính xác cao nhất lớp",earned:false,icon:"🎯"}];return <section className="rounded-2xl border border-violet-400/15 bg-violet-500/5 p-5"><div className="flex items-center gap-2"><Trophy size={19} className="text-violet-300"/><h2 className="font-display text-lg font-bold text-white">Tủ danh hiệu</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{items.map(item=><article key={item.id} className={`rounded-xl border p-4 ${item.earned?"border-yellow-400/30 bg-yellow-500/10":"border-white/5 bg-black/15 opacity-60"}`}><span className="text-2xl">{item.earned?item.icon:"🔒"}</span><strong className="mt-2 block text-sm text-white">{item.name}</strong><small className="text-slate-500">{item.description}</small>{item.earned&&<p className="mt-2 text-[10px] font-bold text-yellow-300">FLEX THÀNH TÍCH ✨</p>}</article>)}</div></section>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-2xl border border-blue-500/15 bg-blue-500/5 p-5"><strong className="text-3xl text-white">{value}</strong><p className="mt-1 text-xs font-bold uppercase tracking-wider text-blue-300">{label}</p></div>}
