"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { AlertTriangle,BookOpen,CalendarCheck,CheckCircle2,ChevronRight,Circle,LayoutDashboard,LogOut,Sparkles,Target } from "lucide-react";
import type { Profile } from "@/components/auth/AuthProvider";
import type { CncLearningRecord } from "@/services/cnc-learning-records";
import { CNC_ASSESSMENT_PLAN,CNC_TOTAL_ASSESSMENTS,cncAssessmentProgress } from "@/services/cnc-progress";
import { fetchMyAttendance } from "@/services/course-attendance";
import { fetchOpenCncLessons } from "@/services/course-lesson-release";
import { fetchMyCncDrawingSubmissions,type CncDrawingSubmission } from "@/services/cnc-drawing-submissions";
import StudentAttendancePanel from "@/components/attendance/StudentAttendancePanel";
import StudentCompetencyCard from "@/components/competencies/StudentCompetencyCard";
import { getSubject } from "@/services/subjects";

type Enrollment={status:string;enrolled_at:string;course:{id:number;name:string;class_label:string;school_year:string;status:string}};
const lessonInfo=[{id:"lesson-1",group:"Chung",title:"Tổng quan máy CNC"},{id:"lesson-2",group:"Tiện CNC",title:"Lập trình tiện"},{id:"lesson-4-turn",group:"Tiện CNC",title:"Vận hành máy tiện"},{id:"lesson-5",group:"Tiện CNC",title:"Gia công tiện"},{id:"lesson-3",group:"Phay CNC",title:"Lập trình phay"},{id:"lesson-4-mill",group:"Phay CNC",title:"Vận hành máy phay"},{id:"lesson-6",group:"Phay CNC",title:"Gia công phay"}];
const labels:Record<string,string>={final:"Kiểm tra cuối bài","exercise-1":"Nhận biết","exercise-2":"Dịch block","exercise-3":"Điền khuyết","exercise-4":"Viết chương trình","exercise-5":"Mô phỏng","machine-operation":"Vận hành máy","tool-setup":"Cài đặt dao","checklist-practice":"Checklist tự luyện",checklist:"Checklist thực hành","rubric-exam":"Thi thực hành tổng hợp"};

export default function StudentLearningDashboard({profile,email,studentId,enrollment,records,onSignOut,preview=false}:{profile:Profile|null;email?:string;studentId:string;enrollment:Enrollment;records:CncLearningRecord[];onSignOut:()=>void;preview?:boolean}){const[tab,setTab]=useState<"overview"|"learning"|"scores"|"attendance">("overview");const progress=cncAssessmentProgress(records);const scored=records.filter(row=>row.total_questions&&row.best_score!==null);const accuracy=scored.length?Math.round(scored.reduce((sum,row)=>sum+100*(row.best_score??0)/(row.total_questions??1),0)/scored.length):0;const next=lessonInfo.find(item=>(CNC_ASSESSMENT_PLAN[item.id]??[]).some(id=>!records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)))??lessonInfo[0];
  const[attention,setAttention]=useState<{reasons:string[];rejected:CncDrawingSubmission[]}|null>(null);
  useEffect(()=>{let cancelled=false;Promise.all([fetchOpenCncLessons(enrollment.course.id).catch(()=>["lesson-1"]),fetchMyAttendance(enrollment.course.id,studentId).catch(()=>[]),fetchMyCncDrawingSubmissions(enrollment.course.id).catch(()=>[])]).then(([openLessons,attendance,submissions])=>{if(cancelled)return;const openedKeys=new Set(openLessons.flatMap(lessonId=>(CNC_ASSESSMENT_PLAN[lessonId]??[]).map(assessmentId=>`${lessonId}:${assessmentId}`)));const openedTotal=openedKeys.size;const inScope=records.filter(row=>openedKeys.has(`${row.lesson_id}:${row.assessment_id}`));const passed=inScope.filter(row=>row.completed).length;const pctOpen=openedTotal?Math.round(passed/openedTotal*100):0;const failed=inScope.filter(row=>row.attempt_count>=3&&!row.completed).length;const absent=attendance.filter(row=>row.status==="absent").length;const late=attendance.filter(row=>row.status==="late").length;const uneven=attendance.length>=3&&(absent+late)/attendance.length>=.3;const reasons=[openedTotal>0&&pctOpen<30?`Bài đã mở: ${passed}/${openedTotal} đạt · ${pctOpen}%`:"",failed?`${failed} bài đã mở chưa đạt sau ≥3 lần`:"",absent?`Vắng ${absent} buổi`:"",late?`Đi muộn ${late} lần`:"",uneven?"Đi học chưa đều":""].filter(Boolean);setAttention({reasons,rejected:submissions.filter(item=>item.status==="rejected")})}).catch(()=>{});return()=>{cancelled=true}},[enrollment.course.id,studentId,records]);
  return <div className="space-y-4 sm:space-y-6">
  <section className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-[#172c46] via-[#0e1c32] to-[#071426] p-4 sm:rounded-3xl sm:p-8"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl"/><div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-300 sm:text-xs sm:tracking-[.16em]">{preview?"Chế độ xem thử · Học sinh":"Không gian học tập của tôi"}</p><h1 className="mt-1.5 truncate font-display text-2xl font-bold text-white sm:mt-2 sm:text-3xl">Chào {profile?.full_name||"bạn"} 👋</h1><p className="mt-1.5 text-xs text-slate-400 sm:mt-2 sm:text-sm">{profile?.class_name?`Lớp ${profile.class_name} · `:""}{enrollment.course.name} · {enrollment.course.school_year}</p>{email&&<p className="mt-1 hidden text-xs text-slate-600 sm:block">{email}</p>}</div><button onClick={onSignOut} aria-label={preview?"Quay lại Dashboard giáo viên":"Đăng xuất"} className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-white/10 text-slate-300 sm:h-auto sm:w-auto sm:gap-2 sm:px-4 sm:py-2 sm:text-sm sm:font-bold"><LogOut size={16}/><span className="hidden sm:inline">{preview?"Quay lại Dashboard giáo viên":"Đăng xuất"}</span></button></div><div className="relative mt-5 sm:mt-6"><div className="mb-2 flex items-end justify-between gap-3 text-xs"><b className="text-cyan-200">Năng lượng học tập</b><span className="whitespace-nowrap font-mono text-[11px] text-slate-400 sm:text-xs">{progress.passed}/{CNC_TOTAL_ASSESSMENTS} · {progress.pct}%</span></div><div className="h-3.5 overflow-hidden rounded-full border border-white/10 bg-[#050914] sm:h-4"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 via-cyan-400 to-sky-300 shadow-[0_0_18px_rgba(56,189,248,.45)]" style={{width:`${progress.pct}%`}}/></div><StudentCompetencyCard courseId={enrollment.course.id} studentId={studentId} records={records}/></div></section>
  <nav className="sticky top-16 z-40 grid grid-cols-4 gap-1 rounded-2xl border border-white/10 bg-[#080d1d]/95 p-1.5 backdrop-blur sm:top-20 sm:flex sm:gap-2 sm:overflow-x-auto sm:p-2">{([{id:"overview",label:"Tổng quan",icon:LayoutDashboard},{id:"learning",label:"Học tập",icon:BookOpen},{id:"scores",label:"Kết quả",icon:Target},{id:"attendance",label:"Điểm danh",icon:CalendarCheck}]as const).map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`inline-flex min-w-0 flex-col items-center justify-center gap-1 rounded-xl px-1 py-2 text-[10px] font-bold sm:shrink-0 sm:flex-row sm:gap-2 sm:px-4 sm:py-3 sm:text-sm ${tab===item.id?"bg-blue-600 text-white":"text-slate-400 hover:bg-white/5"}`}><Icon size={17}/><span className="truncate">{item.label}</span></button>})}</nav>
  {tab==="overview"&&<>{attention&&(attention.reasons.length>0||attention.rejected.length>0)&&<section className="rounded-2xl border border-red-400/20 bg-gradient-to-r from-red-500/10 to-orange-500/5 p-4 sm:p-5"><div className="flex items-center gap-2"><AlertTriangle size={18} className="text-red-300"/><h2 className="font-display text-base font-bold text-white sm:text-lg">Cần chú ý</h2></div>{attention.reasons.length>0&&<ul className="mt-3 space-y-1.5 text-xs text-red-100/80 sm:text-sm">{attention.reasons.map((reason,index)=><li key={index} className="flex items-start gap-2"><span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-300"/>{reason}</li>)}</ul>}{attention.rejected.length>0&&<div className="mt-3 space-y-2">{attention.rejected.map(item=>{const title=lessonInfo.find(lesson=>lesson.id===item.lesson_id)?.title??item.lesson_id;return <Link key={item.id} href={`/lop-hoc/cnc/?bai=${item.lesson_id}`} className="flex items-center justify-between gap-3 rounded-xl border border-red-400/10 bg-black/15 p-3"><div className="min-w-0"><strong className="block truncate text-sm text-white">Nộp lại: {title}</strong>{item.teacher_feedback&&<small className="mt-1 block truncate text-red-200/70">{item.teacher_feedback}</small>}</div><ChevronRight size={16} className="shrink-0 text-red-300"/></Link>})}</div>}</section>}<section className="grid grid-cols-3 gap-2 sm:gap-3"><Stat value={`${progress.pct}%`} label="Tiến độ"/><Stat value={scored.length?`${accuracy}%`:"—"} label="Chính xác"/><Stat value={`${progress.passed}/${CNC_TOTAL_ASSESSMENTS}`} label="Đã đạt"/></section><Link href={`/lop-hoc/cnc/?bai=${next.id}`} className="flex items-center justify-between gap-3 rounded-2xl border border-orange-400/20 bg-gradient-to-r from-orange-500/10 to-transparent p-4 sm:p-5"><div className="min-w-0"><small className="text-[10px] font-bold uppercase tracking-wider text-orange-300 sm:text-xs">Học tiếp theo</small><h2 className="mt-1 truncate font-display text-lg font-bold text-white sm:text-xl">{next.title}</h2><p className="mt-1 text-xs text-slate-400 sm:text-sm">Vào bài học hoặc làm bài kiểm tra tiếp theo.</p></div><ChevronRight className="shrink-0 text-orange-300"/></Link></>}
  {tab==="learning"&&<Learning records={records}/>} {tab==="scores"&&<Scores records={records}/>} {tab==="attendance"&&<StudentAttendancePanel courseId={enrollment.course.id} studentId={studentId} workshop={getSubject("cnc").workshop}/>}<button className="fixed bottom-6 right-6 z-50 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-violet-600 to-blue-600 px-5 py-3 text-sm font-bold text-white shadow-2xl"><Sparkles size={17}/>Hỏi AI học cùng</button></div>}

function Learning({records}:{records:CncLearningRecord[]}){return <div className="space-y-5">{["Chung","Tiện CNC","Phay CNC"].map(group=><section key={group} className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><h2 className="font-display text-xl font-bold text-white">{group}</h2><p className="mt-1 text-sm text-slate-500">Chọn nội dung để học tiếp, xem lại bài giảng hoặc hỏi trợ giảng AI.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{lessonInfo.filter(item=>item.group===group).map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const passed=plan.filter(id=>records.some(row=>row.lesson_id===item.id&&row.assessment_id===id&&row.completed)).length;const started=records.some(row=>row.lesson_id===item.id);const completed=plan.length>0&&passed===plan.length;return <article key={item.id} className="rounded-xl border border-white/5 bg-white/[.02] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-white">{item.title}</strong><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${completed?"bg-emerald-500/10 text-emerald-300":started?"bg-blue-500/10 text-blue-300":"bg-white/5 text-slate-500"}`}>{completed?"Đã hoàn thành":started?"Đang học":"Chưa bắt đầu"}</span></div><div className="mt-4 flex gap-2"><Link href={`/lop-hoc/cnc/?bai=${item.id}`} className="rounded-full bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">{completed?"Xem lại":"Học tiếp"}</Link><button className="rounded-full border border-violet-400/20 px-3 py-1.5 text-xs font-bold text-violet-200">Hỏi AI</button></div></article>})}</div></section>)}</div>}
function Scores({records}:{records:CncLearningRecord[]}){return <div className="space-y-3">{lessonInfo.map(item=>{const plan=CNC_ASSESSMENT_PLAN[item.id]??[];const rows=plan.map(id=>({id,record:records.find(row=>row.lesson_id===item.id&&row.assessment_id===id)}));return <details key={item.id} open={rows.some(row=>row.record)} className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><summary className="cursor-pointer font-bold text-white">{item.title} <span className="float-right text-xs text-cyan-300">{rows.filter(row=>row.record?.completed).length}/{plan.length} đạt</span></summary><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map(({id,record})=>{const pct=record?.total_questions?Math.round(100*(record.best_score??0)/record.total_questions):0;const tone=record?.completed?"border-emerald-500/20 bg-emerald-500/5 hover:border-emerald-400/40":record?.attempt_count&&record.attempt_count>=3?"border-red-500/20 bg-red-500/5 hover:border-red-400/40":record?"border-amber-500/20 bg-amber-500/5 hover:border-amber-400/40":"border-white/5 hover:border-white/15";const bar=record?.completed?"bg-emerald-400":record?.attempt_count&&record.attempt_count>=3?"bg-red-400":"bg-amber-400";return <Link key={id} href={`/lop-hoc/cnc/?bai=${item.id}`} className={`group rounded-xl border p-3 transition hover:-translate-y-0.5 ${tone}`}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs text-slate-400">{record?.completed?<CheckCircle2 size={14} className="text-emerald-400"/>:<Circle size={14} className="text-slate-600"/>}{labels[id]??id}</span><ChevronRight size={14} className="text-slate-600 transition group-hover:translate-x-0.5 group-hover:text-slate-400"/></div><div className="mt-1 flex justify-between"><b className="text-white">{record?`${record.best_score}/${record.total_questions}`:"Chưa làm"}</b>{record&&<span className="text-xs text-slate-500">{record.attempt_count} lần</span>}</div>{record&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/30"><div className={`h-full rounded-full ${bar}`} style={{width:`${pct}%`}}/></div>}</Link>})}</div></details>})}</div>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-xl border border-blue-500/15 bg-blue-500/5 p-3 sm:rounded-2xl sm:p-5"><strong className="text-xl text-white sm:text-3xl">{value}</strong><p className="mt-1 truncate text-[9px] font-bold uppercase tracking-wide text-blue-300 sm:text-xs sm:tracking-wider">{label}</p></div>}
