"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, CalendarCheck, CheckCircle2, Clock3, Route, ShieldAlert, Users } from "lucide-react";
import { CNC_COMPETENCIES, fetchCourseCompetencyPermissions, type CompetencyPermission } from "@/services/cnc-competencies";
import { fetchAttendanceRecords, fetchAttendanceSessions, type AttendanceRecord } from "@/services/course-attendance";
import type { CncLearningRecord } from "@/services/cnc-learning-records";

type OverviewStudent={id:string;name:string;className:string;pct:number;xp:number;records:CncLearningRecord[]};
type DashboardTab="overview"|"progress"|"competencies"|"attendance";

export default function TeacherOverview({courseId,students,onOpenTab,onOpenStudent}:{courseId:number;students:OverviewStudent[];onOpenTab:(tab:DashboardTab)=>void;onOpenStudent:(id:string)=>void}){
  const[permissions,setPermissions]=useState<CompetencyPermission[]>([]);const[attendance,setAttendance]=useState<AttendanceRecord[]>([]);const[sessionCount,setSessionCount]=useState(0);
  useEffect(()=>{let cancelled=false;Promise.all([fetchAttendanceSessions(courseId),fetchCourseCompetencyPermissions(courseId)]).then(async([sessions,permissionRows])=>{const rows=(await Promise.all(sessions.map(item=>fetchAttendanceRecords(item.id).catch(()=>[])))).flat();if(cancelled)return;setPermissions(permissionRows);setSessionCount(sessions.length);setAttendance(rows)}).catch(()=>{/* Migration có thể chưa được chạy; tổng quan học tập vẫn hoạt động. */});return()=>{cancelled=true}},[courseId]);
  const competencyStates=CNC_COMPETENCIES.map(item=>{let approved=0,waiting=0,notPassed=0;students.forEach(student=>{const theory=student.records.some(record=>record.lesson_id===item.lessonId&&record.assessment_id===item.assessmentId&&record.completed);const permission=permissions.find(row=>row.student_id===student.id&&row.competency_id===item.id);if(permission?.status==="approved")approved++;else if(theory)waiting++;else notPassed++});return{...item,approved,waiting,notPassed}});
  const attendanceRate=sessionCount&&students.length?Math.round(attendance.filter(row=>row.status==="present"||row.status==="late").length/(sessionCount*students.length)*100):0;
  const avgProgress=students.length?Math.round(students.reduce((sum,item)=>sum+item.pct,0)/students.length):0;
  const waitingPermissions=competencyStates.reduce((sum,item)=>sum+item.waiting,0);
  const distribution=[{label:"Chưa bắt đầu",count:students.filter(item=>item.pct===0).length,color:"bg-slate-500"},{label:"Đang học",count:students.filter(item=>item.pct>0&&item.pct<50).length,color:"bg-blue-500"},{label:"Gần hoàn thành",count:students.filter(item=>item.pct>=50&&item.pct<80).length,color:"bg-amber-500"},{label:"Hoàn thành tốt",count:students.filter(item=>item.pct>=80).length,color:"bg-emerald-500"}];
  const classPassed=new Map<string,number>();students.forEach(student=>student.records.filter(record=>record.completed).forEach(record=>{const key=`${record.lesson_id}:${record.assessment_id}`;classPassed.set(key,(classPassed.get(key)??0)+1)}));
  const concern=students.map(student=>{const failed=student.records.filter(record=>record.attempt_count>=3&&!record.completed).length;const ownAttendance=attendance.filter(row=>row.student_id===student.id);const absent=ownAttendance.filter(row=>row.status==="absent").length;const late=ownAttendance.filter(row=>row.status==="late").length;const uneven=ownAttendance.length>=3&&(absent+late)/ownAttendance.length>=.3;const passedKeys=new Set(student.records.filter(record=>record.completed).map(record=>`${record.lesson_id}:${record.assessment_id}`));const lateWork=[...classPassed].filter(([key,count])=>students.length>=2&&count/students.length>=.5&&!passedKeys.has(key)).length;const belowClass=avgProgress>=30&&student.pct+20<avgProgress;const reasons=[student.pct<30?`Tiến độ mới ${student.pct}%`:belowClass?`Chậm hơn lớp ${avgProgress-student.pct}%`:"",failed?`${failed} bài chưa đạt sau ≥3 lần`:"",lateWork?`${lateWork} bài đang chậm so với lớp`:"",absent?`Vắng ${absent} buổi`:"",late?`Đi muộn ${late} lần`:"",uneven?"Đi học chưa đều":""].filter(Boolean);return{student,reasons,score:(student.pct<30?3:belowClass?2:0)+failed*3+lateWork*2+absent*2+late+(uneven?2:0)}}).filter(item=>item.reasons.length).sort((a,b)=>b.score-a.score).slice(0,8);
  const activities=useMemo(()=>students.flatMap(student=>student.records.filter(record=>record.completed).map(record=>({student:student.name,time:record.last_activity_at,text:`đạt ${record.assessment_id==="machine-operation"?"kiểm tra vận hành máy":record.assessment_id==="tool-setup"?"kiểm tra cài đặt dao":"một bài kiểm tra"}`}))).sort((a,b)=>Date.parse(b.time)-Date.parse(a.time)).slice(0,6),[students]);
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users size={18}/>} value={String(students.length)} label="Sinh viên" tone="blue"/><Metric icon={<Route size={18}/>} value={`${avgProgress}%`} label="Tiến độ trung bình" tone="violet"/><Metric icon={<CalendarCheck size={18}/>} value={sessionCount?`${attendanceRate}%`:"—"} label="Tham dự trung bình" tone="emerald"/><Metric icon={<AlertTriangle size={18}/>} value={String(waitingPermissions+concern.length)} label="Việc cần xử lý" tone="amber"/></section>
  <section className="rounded-2xl border border-amber-400/20 bg-gradient-to-r from-amber-500/10 to-orange-500/5 p-5"><div className="flex items-center gap-2"><ShieldAlert size={20} className="text-amber-300"/><h3 className="font-display text-lg font-bold text-white">Cần giáo viên xử lý</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Action value={waitingPermissions} label="Chờ cấp quyền" onClick={()=>onOpenTab("competencies")}/><Action value={concern.length} label="Sinh viên cần quan tâm" onClick={()=>onOpenTab("progress")}/><Action value={attendance.filter(row=>row.status==="absent").length} label="Lượt vắng không phép" onClick={()=>onOpenTab("attendance")}/></div></section>
  <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card title="Sinh viên cần quan tâm" icon={<AlertTriangle size={18}/>}>{concern.length?concern.map(item=><button key={item.student.id} onClick={()=>onOpenStudent(item.student.id)} className="mb-2 flex w-full items-center justify-between rounded-xl border border-red-400/10 bg-red-500/5 p-3 text-left"><div><strong className="text-sm text-white">{item.student.name}</strong><small className="mt-1 block text-red-200/70">{item.reasons.join(" · ")}</small></div><ArrowRight size={16} className="text-red-300"/></button>):<Empty text="Chưa có sinh viên thuộc nhóm cần quan tâm."/>}</Card><Card title="Phân bố tiến độ lớp" icon={<Route size={18}/>}>{distribution.map(item=><button key={item.label} onClick={()=>onOpenTab("progress")} className="mb-3 block w-full text-left"><div className="mb-1 flex justify-between text-sm"><span className="text-slate-300">{item.label}</span><strong className="text-white">{item.count}</strong></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className={`h-full ${item.color}`} style={{width:`${students.length?item.count/students.length*100:0}%`}}/></div></button>)}</Card></section>
  <section><Card title="Hoạt động gần đây" icon={<Clock3 size={18}/>}>{activities.length?<div className="grid gap-2 md:grid-cols-2">{activities.map((item,index)=><div key={`${item.student}-${item.time}-${index}`} className="flex gap-3 rounded-xl bg-white/[.02] p-3"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-300"/><div><p className="text-sm text-slate-300"><strong className="text-white">{item.student}</strong> {item.text}</p><small className="text-slate-500">{new Date(item.time).toLocaleString("vi-VN")}</small></div></div>)}</div>:<Empty text="Chưa có hoạt động học tập."/>}</Card></section></div>
}

function Metric({icon,value,label,tone}:{icon:React.ReactNode;value:string;label:string;tone:string}){const styles:Record<string,string>={blue:"border-blue-500/20 bg-blue-500/8 text-blue-300",violet:"border-violet-500/20 bg-violet-500/8 text-violet-300",emerald:"border-emerald-500/20 bg-emerald-500/8 text-emerald-300",amber:"border-amber-500/20 bg-amber-500/8 text-amber-300"};return <div className={`rounded-2xl border p-5 ${styles[tone]}`}><div className="flex items-center gap-2">{icon}<span className="text-xs font-semibold uppercase tracking-wider">{label}</span></div><strong className="mt-3 block text-3xl text-white">{value}</strong></div>}
function Action({value,label,onClick}:{value:number;label:string;onClick:()=>void}){return <button onClick={onClick} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/15 p-4 text-left"><span><strong className="block text-2xl text-white">{value}</strong><small className="text-slate-400">{label}</small></span><ArrowRight size={17} className="text-amber-300"/></button>}
function Card({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><div className="mb-4 flex items-center gap-2 text-violet-300">{icon}<h3 className="font-display text-lg font-bold text-white">{title}</h3></div>{children}</article>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">{text}</p>}
