"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, Search, Target, Users } from "lucide-react";
import { CNC_ASSESSMENT_PLAN, CNC_TOTAL_ASSESSMENTS } from "@/services/cnc-progress";
import type { CncLearningRecord } from "@/services/cnc-learning-records";
import { cncAchievements } from "@/services/cnc-achievements";

type GradeStudent={id:string;name:string;className:string;pct:number;xp:number;records:CncLearningRecord[]};
const lessons=[
  {id:"lesson-1",short:"Bài 1",title:"An toàn lao động"},{id:"lesson-2",short:"Bài 2",title:"Lập trình tiện"},{id:"lesson-3",short:"Bài 3",title:"Lập trình phay"},
  {id:"lesson-4-turn",short:"Bài 4T",title:"Vận hành máy tiện"},{id:"lesson-4-mill",short:"Bài 4P",title:"Vận hành máy phay"},{id:"lesson-5",short:"Bài 5",title:"Gia công tiện"},{id:"lesson-6",short:"Bài 6",title:"Gia công phay"},
];
const labels:Record<string,string>={final:"Cuối bài","exercise-1":"Nhận biết","exercise-2":"Dịch block","exercise-3":"Điền khuyết","exercise-4":"Viết CT","exercise-5":"Mô phỏng","machine-operation":"Vận hành","tool-setup":"Cài dao"};

export default function TeacherProgressGradebook({students,selectedId,onSelect}:{students:GradeStudent[];selectedId?:string;onSelect:(id:string)=>void}){
  const[lessonId,setLessonId]=useState("lesson-2");const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[scoreMode,setScoreMode]=useState<"best"|"latest">("best");
  const selected=students.find(item=>item.id===selectedId)??students[0]??null;const assessments=useMemo(()=>CNC_ASSESSMENT_PLAN[lessonId]??[],[lessonId]);
  const scored=students.flatMap(item=>item.records).filter(item=>item.total_questions&&item.latest_score!==null);const avgScore=scored.length?Math.round(scored.reduce((sum,item)=>sum+((item.best_score??item.latest_score??0)/(item.total_questions??1))*100,0)/scored.length):0;
  const avgProgress=students.length?Math.round(students.reduce((sum,item)=>sum+item.pct,0)/students.length):0;const atRisk=students.filter(item=>item.records.some(record=>record.attempt_count>=3&&!record.completed)).length;
  const filtered=useMemo(()=>students.filter(item=>{const matches=`${item.name} ${item.className}`.toLowerCase().includes(query.toLowerCase());const lessonRecords=item.records.filter(record=>record.lesson_id===lessonId);if(status==="passed")return matches&&assessments.every(id=>lessonRecords.some(record=>record.assessment_id===id&&record.completed));if(status==="retry")return matches&&lessonRecords.some(record=>record.attempt_count>=1&&!record.completed);if(status==="not-started")return matches&&!lessonRecords.length;return matches}),[students,query,status,lessonId,assessments]);
  return <div className="space-y-5">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users size={18}/>} value={String(students.length)} label="Sinh viên" tone="blue"/><Metric icon={<BarChart3 size={18}/>} value={`${avgProgress}%`} label="Tiến độ trung bình" tone="violet"/><Metric icon={<Target size={18}/>} value={scored.length?`${avgScore}%`:"—"} label="Điểm trung bình" tone="emerald"/><Metric icon={<AlertTriangle size={18}/>} value={String(atRisk)} label="Cần hỗ trợ" tone="amber"/></section>
    <section className="rounded-2xl border border-white/10 bg-[#0B1020] p-4 sm:p-5"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-52 flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm tên hoặc lớp..." className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-10 pr-3 text-sm text-white outline-none focus:border-blue-400/50"/></div><select value={lessonId} onChange={event=>setLessonId(event.target.value)} className="rounded-xl border border-white/10 bg-[#080d1d] px-3 py-2.5 text-sm text-white">{lessons.map(item=><option key={item.id} value={item.id}>{item.short} · {item.title}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border border-white/10 bg-[#080d1d] px-3 py-2.5 text-sm text-white"><option value="all">Tất cả trạng thái</option><option value="passed">Đã đạt toàn bài</option><option value="retry">Cần làm lại</option><option value="not-started">Chưa bắt đầu</option></select><div className="flex rounded-xl border border-white/10 bg-black/20 p-1"><button onClick={()=>setScoreMode("best")} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${scoreMode==="best"?"bg-blue-600 text-white":"text-slate-400"}`}>Cao nhất</button><button onClick={()=>setScoreMode("latest")} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${scoreMode==="latest"?"bg-blue-600 text-white":"text-slate-400"}`}>Gần nhất</button></div></div>
      <div className="mt-4 overflow-auto rounded-xl border border-white/10"><table className="min-w-full border-collapse text-sm"><thead className="sticky top-0 z-20 bg-[#111a2e]"><tr><th className="sticky left-0 z-30 min-w-56 border-b border-r border-white/10 bg-[#111a2e] p-3 text-left text-slate-300">Sinh viên</th><th className="min-w-28 border-b border-white/10 p-3 text-center text-slate-300">Tiến độ</th>{assessments.map((id,index)=><th key={id} className="min-w-28 border-b border-white/10 p-3 text-center text-slate-300"><span className="block text-[10px] text-blue-300">BT {index+1}</span>{labels[id]??id}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id} className={selected?.id===item.id?"bg-blue-500/5":"hover:bg-white/[.02]"}><td className="sticky left-0 z-10 border-b border-r border-white/5 bg-[#0B1020] p-3"><button onClick={()=>onSelect(item.id)} className="flex w-full items-center gap-3 text-left"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-cyan-400 font-bold text-white">{item.name.split(" ").at(-1)?.[0]}</span><span><strong className="block text-white">{item.name}</strong><small className="text-slate-500">{item.className}</small></span></button></td><td className="border-b border-white/5 p-3"><div className="mx-auto w-24"><div className="mb-1 flex justify-between text-[10px] text-slate-400"><span>{item.xp}/{CNC_TOTAL_ASSESSMENTS}</span><b>{item.pct}%</b></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-300" style={{width:`${item.pct}%`}}/></div></div></td>{assessments.map(id=><ScoreCell key={id} record={item.records.find(record=>record.lesson_id===lessonId&&record.assessment_id===id)} mode={scoreMode} onClick={()=>onSelect(item.id)}/>)}</tr>)}{!filtered.length&&<tr><td colSpan={assessments.length+2} className="p-10 text-center text-slate-500">Không có sinh viên phù hợp bộ lọc.</td></tr>}</tbody></table></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><Legend color="bg-emerald-500" text="Đạt"/><Legend color="bg-amber-500" text="Chưa đạt"/><Legend color="bg-red-500" text="Chưa đạt ≥3 lần"/><Legend color="bg-slate-600" text="Chưa làm"/></div></section>
    {selected&&<StudentDetail student={selected} badges={cncAchievements(selected.records,[]).filter(item=>item.group==="assessment"&&item.earned)}/>}</div>
}

function ScoreCell({record,mode,onClick}:{record?:CncLearningRecord;mode:"best"|"latest";onClick:()=>void}){if(!record)return <td className="border-b border-white/5 p-3 text-center"><span className="inline-flex min-w-16 justify-center rounded-lg bg-slate-500/10 px-2 py-2 font-bold text-slate-500">—</span></td>;const score=mode==="best"?record.best_score:record.latest_score;const tone=record.completed?"border-emerald-500/20 bg-emerald-500/10 text-emerald-300":record.attempt_count>=3?"border-red-500/25 bg-red-500/10 text-red-300":"border-amber-500/20 bg-amber-500/10 text-amber-300";return <td className="border-b border-white/5 p-3 text-center"><button title={`${record.attempt_count} lần làm`} onClick={onClick} className={`min-w-16 rounded-lg border px-2 py-1.5 font-bold ${tone}`}>{score??0}/{record.total_questions}<small className="block text-[9px] font-normal opacity-70">{record.attempt_count} lần</small></button></td>}
function StudentDetail({student,badges}:{student:GradeStudent;badges:Array<{icon:string;name:string}>}){return <section className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Hồ sơ chi tiết</p><h3 className="mt-1 font-display text-xl font-bold text-white">{student.name}</h3><p className="text-sm text-slate-500">{student.className} · Đã đạt {student.xp}/{CNC_TOTAL_ASSESSMENTS} bài kiểm tra</p>{badges.length>0&&<div className="mt-2 flex flex-wrap gap-2">{badges.map(item=><span key={item.name} className="rounded-full border border-yellow-400/20 bg-yellow-500/10 px-2.5 py-1 text-[10px] font-bold text-yellow-200">{item.icon} {item.name}</span>)}</div>}</div><span className="rounded-full bg-blue-500/10 px-4 py-2 font-mono text-sm font-bold text-blue-200">{student.pct}%</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{lessons.map(lesson=>{const plan=CNC_ASSESSMENT_PLAN[lesson.id]??[];const records=plan.map(id=>({id,record:student.records.find(row=>row.lesson_id===lesson.id&&row.assessment_id===id)}));const passed=records.filter(item=>item.record?.completed).length;return <article key={lesson.id} className="rounded-xl border border-white/5 bg-black/15 p-4"><div className="flex justify-between gap-3"><strong className="text-sm text-white">{lesson.short} · {lesson.title}</strong><span className="text-xs font-bold text-blue-300">{passed}/{plan.length} đạt</span></div><div className="mt-3 space-y-2">{records.map((item,index)=><div key={item.id} className="flex items-center justify-between gap-3 text-xs"><span className="flex items-center gap-2 text-slate-400">{item.record?.completed?<CheckCircle2 size={14} className="text-emerald-400"/>:<span className="h-3.5 w-3.5 rounded-full border border-slate-600"/>}BT {index+1} · {labels[item.id]??item.id}</span><b className={item.record?.completed?"text-emerald-300":item.record?"text-amber-300":"text-slate-600"}>{item.record?`${item.record.best_score??item.record.latest_score}/${item.record.total_questions}`:"Chưa làm"}</b></div>)}</div></article>})}</div></section>}
function Metric({icon,value,label,tone}:{icon:React.ReactNode;value:string;label:string;tone:string}){const styles:Record<string,string>={blue:"border-blue-500/20 bg-blue-500/8 text-blue-300",violet:"border-violet-500/20 bg-violet-500/8 text-violet-300",emerald:"border-emerald-500/20 bg-emerald-500/8 text-emerald-300",amber:"border-amber-500/20 bg-amber-500/8 text-amber-300"};return <div className={`rounded-2xl border p-5 ${styles[tone]}`}><div className="flex items-center gap-2">{icon}<span className="text-xs font-semibold uppercase tracking-wider">{label}</span></div><strong className="mt-3 block text-3xl text-white">{value}</strong></div>}
function Legend({color,text}:{color:string;text:string}){return <span className="inline-flex items-center gap-1.5"><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{text}</span>}
