"use client";

import { useCallback, useEffect, useState } from "react";
import { CalendarCheck, Clock3, Copy, LockKeyhole, Plus, RefreshCw, Users } from "lucide-react";
import { closeAttendanceSession, createAttendanceSession, fetchAttendanceRecords, fetchAttendanceSessions, setAttendanceRecord, type AttendanceRecord, type AttendanceSession, type AttendanceStatus } from "@/services/course-attendance";

type Student={id:string;name:string;className:string};
const statusMeta:Record<AttendanceStatus,{label:string;style:string}>={present:{label:"Có mặt",style:"text-emerald-300"},late:{label:"Đi muộn",style:"text-amber-300"},excused:{label:"Vắng có phép",style:"text-blue-300"},absent:{label:"Vắng không phép",style:"text-red-300"}};

export default function TeacherAttendancePanel({courseId,students}:{courseId:number;students:Student[]}){
  const[sessions,setSessions]=useState<AttendanceSession[]>([]);const[selectedId,setSelectedId]=useState<number|null>(null);const[records,setRecords]=useState<AttendanceRecord[]>([]);const[creating,setCreating]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const now=new Date();const[title,setTitle]=useState("Thực hành CNC");const[startsAt,setStartsAt]=useState(new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16));
  const selected=sessions.find(item=>item.id===selectedId)??null;
  const loadSessions=useCallback(()=>fetchAttendanceSessions(courseId).then(rows=>{setSessions(rows);setSelectedId(current=>rows.some(item=>item.id===current)?current:rows[0]?.id??null)}).catch(cause=>setError(cause instanceof Error?cause.message:"Không tải được phiên điểm danh.")),[courseId]);
  useEffect(()=>{void loadSessions()},[loadSessions]);
  useEffect(()=>{if(!selectedId)return;void fetchAttendanceRecords(selectedId).then(setRecords).catch(cause=>setError(cause instanceof Error?cause.message:"Không tải được kết quả điểm danh."))},[selectedId]);
  async function createSession(){setBusy(true);setError("");try{const item=await createAttendanceSession({courseId,title,startsAt,durationMinutes:60,lateMinutes:15});setSessions(current=>[item,...current]);setSelectedId(item.id);setCreating(false)}catch(cause){setError(cause instanceof Error?cause.message:"Không tạo được phiên điểm danh.")}finally{setBusy(false)}}
  async function mark(studentId:string,status:AttendanceStatus){if(!selected)return;setBusy(true);try{await setAttendanceRecord(selected.id,studentId,status);setRecords(await fetchAttendanceRecords(selected.id))}catch(cause){setError(cause instanceof Error?cause.message:"Không cập nhật được điểm danh.")}finally{setBusy(false)}}
  const presentCount=records.filter(item=>item.status==="present"||item.status==="late").length;
  return <section className="rounded-2xl border border-white/10 bg-[#0B1020] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-300">Tham dự offline</p><h3 className="mt-1 font-display text-2xl font-bold text-white">Điểm danh khóa học</h3><p className="mt-1 text-sm text-slate-500">Mã 6 số hiệu lực 60 phút; sau 15 phút hệ thống ghi nhận đi muộn.</p></div><button onClick={()=>setCreating(value=>!value)} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/>Tạo buổi điểm danh</button></div>
  {creating&&<div className="mt-5 grid gap-3 rounded-2xl border border-orange-400/20 bg-orange-500/5 p-4 sm:grid-cols-[1fr_1fr_auto]"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nội dung buổi học" className="rounded-xl border border-white/10 bg-[#080d1d] px-4 py-3 text-sm text-white"/><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="rounded-xl border border-white/10 bg-[#080d1d] px-4 py-3 text-sm text-white"/><button disabled={busy||!title.trim()} onClick={createSession} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Mở phiên</button></div>}
  {error&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
  <div className="mt-5 grid gap-5 lg:grid-cols-[.75fr_1.4fr]"><div><div className="mb-3 flex items-center justify-between"><strong className="text-sm text-white">Các buổi học</strong><button aria-label="Làm mới" onClick={()=>void loadSessions()} className="text-slate-400"><RefreshCw size={16}/></button></div><div className="space-y-2">{sessions.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`w-full rounded-xl border p-3 text-left ${selectedId===item.id?"border-cyan-400/40 bg-cyan-500/10":"border-white/5 bg-white/[.02]"}`}><div className="flex justify-between gap-2"><strong className="text-sm text-white">{item.title}</strong><span className={item.status==="open"?"text-xs font-bold text-emerald-300":"text-xs text-slate-500"}>{item.status==="open"?"Đang mở":"Đã khóa"}</span></div><small className="mt-1 block text-slate-500">{new Date(item.starts_at).toLocaleString("vi-VN")}</small></button>)}{!sessions.length&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">Chưa có buổi điểm danh.</p>}</div></div>
  <div>{selected?<><div className="rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-500/10 to-blue-500/5 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><small className="font-bold uppercase tracking-wider text-cyan-300">Mã điểm danh</small><div className="mt-1 flex items-center gap-3"><strong className="font-mono text-4xl tracking-[.18em] text-white">{selected.code}</strong><button onClick={()=>navigator.clipboard.writeText(selected.code)} className="text-cyan-300"><Copy size={18}/></button></div></div><div className="text-right text-sm text-slate-400"><p className="flex items-center justify-end gap-2"><Users size={15}/>{presentCount}/{students.length} đã tham dự</p><p className="mt-1 flex items-center justify-end gap-2"><Clock3 size={15}/>Đóng {new Date(selected.closes_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</p></div></div>{selected.status==="open"&&<button onClick={async()=>{await closeAttendanceSession(selected.id);await loadSessions()}} className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-slate-300"><LockKeyhole size={14}/>Khóa phiên</button>}</div>
  <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-white/10 text-xs uppercase text-slate-500"><th className="p-3">Sinh viên</th><th className="p-3">Trạng thái</th><th className="p-3">Thời gian</th><th className="p-3">Điều chỉnh</th></tr></thead><tbody>{students.map(student=>{const record=records.find(item=>item.student_id===student.id);return <tr key={student.id} className="border-b border-white/5"><td className="p-3"><strong className="text-white">{student.name}</strong><small className="block text-slate-500">{student.className}</small></td><td className={`p-3 font-bold ${record?statusMeta[record.status].style:"text-slate-500"}`}>{record?statusMeta[record.status].label:"Chưa điểm danh"}</td><td className="p-3 text-slate-400">{record?.checked_in_at?new Date(record.checked_in_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td className="p-3"><select disabled={busy} value={record?.status??""} onChange={e=>void mark(student.id,e.target.value as AttendanceStatus)} className="rounded-lg border border-white/10 bg-[#080d1d] px-3 py-2 text-xs text-white"><option value="" disabled>Chọn</option>{Object.entries(statusMeta).map(([value,meta])=><option key={value} value={value}>{meta.label}</option>)}</select></td></tr>})}</tbody></table></div></>:<div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-white/10 text-sm text-slate-500"><CalendarCheck size={30}/><span>Chọn hoặc tạo một buổi điểm danh.</span></div>}</div></div></section>
}
