"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CalendarCheck, Clock3, Copy, LockKeyhole, Plus, RefreshCw, UserCheck, Users } from "lucide-react";
import { closeAttendanceSession, createAttendanceSession, fetchAttendanceRecords, fetchAttendanceSessions, setAttendanceRecord, type AttendanceRecord, type AttendanceSession, type AttendanceStatus } from "@/services/course-attendance";

type Student={id:string;name:string;className:string};
const statusMeta:Record<AttendanceStatus,{label:string;style:string}>={present:{label:"Có mặt",style:"text-emerald-300"},late:{label:"Đi muộn",style:"text-amber-300"},excused:{label:"Vắng có phép",style:"text-blue-300"},absent:{label:"Vắng không phép",style:"text-red-300"}};

export default function TeacherAttendancePanel({courseId,students}:{courseId:number;students:Student[]}){
  const[sessions,setSessions]=useState<AttendanceSession[]>([]);const[selectedId,setSelectedId]=useState<number|null>(null);const[records,setRecords]=useState<AttendanceRecord[]>([]);const[allRecords,setAllRecords]=useState<AttendanceRecord[]>([]);const[creating,setCreating]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const now=new Date();const[title,setTitle]=useState("Thực hành CNC");const[startsAt,setStartsAt]=useState(new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16));
  const selected=sessions.find(item=>item.id===selectedId)??null;
  const loadSessions=useCallback(()=>fetchAttendanceSessions(courseId).then(rows=>{setSessions(rows);setSelectedId(current=>rows.some(item=>item.id===current)?current:rows[0]?.id??null)}).catch(cause=>setError(cause instanceof Error?cause.message:"Không tải được phiên điểm danh.")),[courseId]);
  useEffect(()=>{void loadSessions()},[loadSessions]);
  useEffect(()=>{let cancelled=false;Promise.all(sessions.map(session=>fetchAttendanceRecords(session.id).catch(()=>[]))).then(rows=>{if(!cancelled)setAllRecords(rows.flat())});return()=>{cancelled=true}},[sessions]);
  useEffect(()=>{if(!selectedId)return;void fetchAttendanceRecords(selectedId).then(setRecords).catch(cause=>setError(cause instanceof Error?cause.message:"Không tải được kết quả điểm danh."))},[selectedId]);
  async function createSession(){setBusy(true);setError("");try{const item=await createAttendanceSession({courseId,title,startsAt,durationMinutes:60,lateMinutes:15});setSessions(current=>[item,...current]);setSelectedId(item.id);setCreating(false)}catch(cause){setError(cause instanceof Error?cause.message:"Không tạo được phiên điểm danh.")}finally{setBusy(false)}}
  async function mark(studentId:string,status:AttendanceStatus){if(!selected)return;setBusy(true);try{await setAttendanceRecord(selected.id,studentId,status);setRecords(await fetchAttendanceRecords(selected.id))}catch(cause){setError(cause instanceof Error?cause.message:"Không cập nhật được điểm danh.")}finally{setBusy(false)}}
  const presentCount=records.filter(item=>item.status==="present"||item.status==="late").length;
  const summary=students.map(student=>{const own=allRecords.filter(row=>row.student_id===student.id);const present=own.filter(row=>row.status==="present").length;const late=own.filter(row=>row.status==="late").length;const excused=own.filter(row=>row.status==="excused").length;const absent=own.filter(row=>row.status==="absent").length;const rate=sessions.length?Math.round((present+late)/sessions.length*100):0;let streak=0;for(const session of sessions.toSorted((a,b)=>Date.parse(b.starts_at)-Date.parse(a.starts_at))){const row=own.find(record=>record.session_id===session.id);if(row?.status==="present"||row?.status==="late")streak++;else break}return{...student,present,late,excused,absent,rate,streak}});const classRate=sessions.length&&students.length?Math.round(allRecords.filter(row=>row.status==="present"||row.status==="late").length/(sessions.length*students.length)*100):0;const perfect=summary.filter(item=>sessions.length>0&&item.present===sessions.length).length;const concern=summary.filter(item=>item.absent>=2||item.late>=3||(sessions.length>=3&&item.rate<75)).length;
  return <div className="space-y-5"><AttendanceSummary sessions={sessions.length} classRate={classRate} perfect={perfect} concern={concern} rows={summary}/><section className="rounded-2xl border border-white/10 bg-[#0B1020] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-300">Tham dự offline</p><h3 className="mt-1 font-display text-2xl font-bold text-white">Điểm danh khóa học</h3><p className="mt-1 text-sm text-slate-500">Mã 6 số hiệu lực 60 phút; sau 15 phút hệ thống ghi nhận đi muộn.</p></div><button onClick={()=>setCreating(value=>!value)} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/>Tạo buổi điểm danh</button></div>
  {creating&&<div className="mt-5 grid gap-3 rounded-2xl border border-orange-400/20 bg-orange-500/5 p-4 sm:grid-cols-[1fr_1fr_auto]"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nội dung buổi học" className="rounded-xl border border-white/10 bg-[#080d1d] px-4 py-3 text-sm text-white"/><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="rounded-xl border border-white/10 bg-[#080d1d] px-4 py-3 text-sm text-white"/><button disabled={busy||!title.trim()} onClick={createSession} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Mở phiên</button></div>}
  {error&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
  <div className="mt-5 grid gap-5 lg:grid-cols-[.75fr_1.4fr]"><div><div className="mb-3 flex items-center justify-between"><strong className="text-sm text-white">Các buổi học</strong><button aria-label="Làm mới" onClick={()=>void loadSessions()} className="text-slate-400"><RefreshCw size={16}/></button></div><div className="space-y-2">{sessions.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`w-full rounded-xl border p-3 text-left ${selectedId===item.id?"border-cyan-400/40 bg-cyan-500/10":"border-white/5 bg-white/[.02]"}`}><div className="flex justify-between gap-2"><strong className="text-sm text-white">{item.title}</strong><span className={item.status==="open"?"text-xs font-bold text-emerald-300":"text-xs text-slate-500"}>{item.status==="open"?"Đang mở":"Đã khóa"}</span></div><small className="mt-1 block text-slate-500">{new Date(item.starts_at).toLocaleString("vi-VN")}</small></button>)}{!sessions.length&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">Chưa có buổi điểm danh.</p>}</div></div>
  <div>{selected?<><div className="rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-500/10 to-blue-500/5 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><small className="font-bold uppercase tracking-wider text-cyan-300">Mã điểm danh</small><div className="mt-1 flex items-center gap-3"><strong className="font-mono text-4xl tracking-[.18em] text-white">{selected.code}</strong><button onClick={()=>navigator.clipboard.writeText(selected.code)} className="text-cyan-300"><Copy size={18}/></button></div></div><div className="text-right text-sm text-slate-400"><p className="flex items-center justify-end gap-2"><Users size={15}/>{presentCount}/{students.length} đã tham dự</p><p className="mt-1 flex items-center justify-end gap-2"><Clock3 size={15}/>Đóng {new Date(selected.closes_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</p></div></div>{selected.status==="open"&&<button onClick={async()=>{await closeAttendanceSession(selected.id);await loadSessions()}} className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-slate-300"><LockKeyhole size={14}/>Khóa phiên</button>}</div>
  <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-white/10 text-xs uppercase text-slate-500"><th className="p-3">Sinh viên</th><th className="p-3">Trạng thái</th><th className="p-3">Thời gian</th><th className="p-3">Điều chỉnh</th></tr></thead><tbody>{students.map(student=>{const record=records.find(item=>item.student_id===student.id);return <tr key={student.id} className="border-b border-white/5"><td className="p-3"><strong className="text-white">{student.name}</strong><small className="block text-slate-500">{student.className}</small></td><td className={`p-3 font-bold ${record?statusMeta[record.status].style:"text-slate-500"}`}>{record?statusMeta[record.status].label:"Chưa điểm danh"}</td><td className="p-3 text-slate-400">{record?.checked_in_at?new Date(record.checked_in_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td className="p-3"><select disabled={busy} value={record?.status??""} onChange={e=>void mark(student.id,e.target.value as AttendanceStatus)} className="rounded-lg border border-white/10 bg-[#080d1d] px-3 py-2 text-xs text-white"><option value="" disabled>Chọn</option>{Object.entries(statusMeta).map(([value,meta])=><option key={value} value={value}>{meta.label}</option>)}</select></td></tr>})}</tbody></table></div></>:<div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-white/10 text-sm text-slate-500"><CalendarCheck size={30}/><span>Chọn hoặc tạo một buổi điểm danh.</span></div>}</div></div></section></div>
}

function AttendanceSummary({sessions,classRate,perfect,concern,rows}:{sessions:number;classRate:number;perfect:number;concern:number;rows:Array<Student&{present:number;late:number;excused:number;absent:number;rate:number;streak:number}>}){return <section className="rounded-2xl border border-white/10 bg-[#0B1020] p-5"><div className="flex items-center gap-2"><CalendarCheck size={19} className="text-cyan-300"/><h3 className="font-display text-xl font-bold text-white">Tổng kết điểm danh</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryMetric icon={<CalendarCheck size={16}/>} value={String(sessions)} label="Buổi đã tổ chức"/><SummaryMetric icon={<Users size={16}/>} value={sessions?`${classRate}%`:"—"} label="Tham dự trung bình"/><SummaryMetric icon={<UserCheck size={16}/>} value={String(perfect)} label="Chuyên cần"/><SummaryMetric icon={<AlertTriangle size={16}/>} value={String(concern)} label="Cần nhắc nhở" danger/></div><div className="mt-4 overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white/[.03] text-xs uppercase text-slate-500"><tr><th className="p-3 text-left">Sinh viên</th><th className="p-3">Có mặt</th><th className="p-3">Đi muộn</th><th className="p-3">Có phép</th><th className="p-3">Không phép</th><th className="p-3">Tỷ lệ</th><th className="p-3">Chuỗi hiện tại</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/5"><td className="p-3"><strong className="text-white">{row.name}</strong><small className="block text-slate-500">{row.className}</small></td><td className="p-3 text-center text-emerald-300">{row.present}</td><td className={`p-3 text-center ${row.late>=3?"font-bold text-amber-300":"text-slate-400"}`}>{row.late}</td><td className="p-3 text-center text-blue-300">{row.excused}</td><td className={`p-3 text-center ${row.absent>=2?"font-bold text-red-300":"text-slate-400"}`}>{row.absent}</td><td className="p-3 text-center"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.rate>=90?"bg-emerald-500/10 text-emerald-300":row.rate>=75?"bg-amber-500/10 text-amber-300":"bg-red-500/10 text-red-300"}`}>{sessions?`${row.rate}%`:"—"}</span></td><td className="p-3 text-center text-violet-300">{row.streak} buổi</td></tr>)}</tbody></table></div></section>}
function SummaryMetric({icon,value,label,danger=false}:{icon:React.ReactNode;value:string;label:string;danger?:boolean}){return <div className={`rounded-xl border p-4 ${danger?"border-red-400/15 bg-red-500/5 text-red-300":"border-cyan-400/10 bg-cyan-500/5 text-cyan-300"}`}><div className="flex items-center gap-2 text-xs font-bold uppercase">{icon}{label}</div><strong className="mt-2 block text-2xl text-white">{value}</strong></div>}
