'use client';
import { useEffect, useState } from 'react';
import { getPolicyMonth, getPolicySessions, savePolicyMonth, POLICY_SCORES, type MonthPolicy } from '@/lib/tro-giang/policy';
import { fetchAssistants, type TaAssistant, type TaSessionRow } from '@/lib/tro-giang/queries';
import { getSupabase } from '@/services/supabase';
import { SESSION_TYPE_META, STATUS_META } from '@/lib/tro-giang/constants';
import PolicyMonthSummary from './PolicyMonthSummary';
import PolicySessionEditor from './PolicySessionEditor';
import { useToast } from '@/components/ui/Toast';
const cls='mt-1 w-full rounded-xl border border-white/15 bg-[#0B1020] px-3 py-2 text-white';
export default function PolicyMonthlyReview({month,reloadKey=0}:{month:string;reloadKey?:number}){
 const [assistants,setAssistants]=useState<TaAssistant[]>([]);const [selected,setSelected]=useState('');const [error,setError]=useState('');
 useEffect(()=>{let active=true;fetchAssistants().then(a=>{if(active){setAssistants(a);setSelected(a[0]?.id??'')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 return <div className="space-y-4">{error&&<p role="alert" className="text-red-300">{error}</p>}<label className="block text-sm text-slate-300">Trợ giảng<select className={cls} value={selected} onChange={e=>setSelected(e.target.value)}>{assistants.map(a=><option key={a.id} value={a.id}>{a.full_name}{!a.active?' · ngừng hoạt động':''}</option>)}</select></label>{selected&&<Review key={`${selected}-${month}-${reloadKey}`} id={selected} month={month}/>}</div>;
}
function Review({id,month}:{id:string;month:string}){
 const [score,setScore]=useState<MonthPolicy|null>(null);const [sessions,setSessions]=useState<TaSessionRow[]>([]);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [editing,setEditing]=useState<TaSessionRow|null>(null);
 const [audit,setAudit]=useState<{id:number;action:string;created_at:string}[]>([]);
 useEffect(()=>{let active=true;Promise.all([getPolicyMonth(id,month),getPolicySessions(id,month),getSupabase().from('ta_policy_audit').select('id,action,created_at').eq('assistant_id',id).eq('month',month).order('created_at',{ascending:false}).limit(12)]).then(([s,rows,history])=>{if(active){setScore(s);setSessions(rows);setAudit(history.data??[]);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id,month,revision]);
 return <div className="space-y-5">{error&&<p role="alert" className="rounded-xl bg-red-500/10 p-4 text-red-200">{error}<button className="ml-3 underline" onClick={()=>setRevision(r=>r+1)}>Thử lại</button></p>}{score?<><PolicyMonthSummary score={score}/><ReviewForm key={`${revision}`} score={score} onSaved={()=>setRevision(r=>r+1)}/></>:!error&&<p className="text-slate-400">Đang tải bảng tháng…</p>}
 <section className="space-y-3"><h3 className="font-semibold text-white">Công trong tháng · {sessions.length} buổi</h3>{sessions.map(s=><div key={s.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3 text-sm text-slate-300"><div><b className="text-white">{s.work_date} · {SESSION_TYPE_META[s.session_type].label}</b><p>{s.class_label} · {STATUS_META[s.status].label} {s.policy?.teaching_minutes?`· chữa bài ${s.policy.teaching_minutes} phút`:''}</p></div><button className="shrink-0 rounded-lg border border-white/15 px-3 py-2" onClick={()=>setEditing(s)}>Xem / sửa</button></div>)}</section>
 {editing&&<PolicySessionEditor key={editing.id} session={editing} onCancel={()=>setEditing(null)} onSaved={()=>{setEditing(null);setRevision(r=>r+1)}}/>}
 {!!audit.length&&<details className="rounded-xl border border-white/10 p-3 text-sm text-slate-400"><summary>Nhật ký thay đổi gần đây</summary><ul className="mt-2 space-y-1">{audit.map(a=><li key={a.id}>{new Date(a.created_at).toLocaleString('vi-VN')} · {({close_month:'Chốt và công bố tháng',save_review:'Lưu / điều chỉnh điểm',reopen_after_session_edit:'Mở lại tháng do sửa công',insert_session:'Ghi buổi',update_session:'Sửa / duyệt buổi'} as Record<string,string>)[a.action]??a.action}</li>)}</ul></details>}
 </div>;
}
function ReviewForm({score,onSaved}:{score:MonthPolicy;onSaved:()=>void}){
 const [scores,setScores]=useState(score.overrides);const [rate,setRate]=useState(score.hourly_rate?.toString()??'');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const toast=useToast();
 async function save(close:boolean){if(!note.trim()){toast('error','Nhập lý do chấm / điều chỉnh.');return}if(rate&&(!Number.isInteger(Number(rate))||Number(rate)<=0)){toast('error','Đơn giá phải là số nguyên dương.');return}setBusy(true);try{await savePolicyMonth(score.assistant_id,score.month,scores,rate?Number(rate):null,note,close);toast('success',close?'Đã chốt và công bố tháng.':'Đã lưu điểm; tháng đang mở.');onSaved()}catch(e){toast('error',e instanceof Error?e.message:'Không lưu được')}finally{setBusy(false)}}
 function csv(){const cell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const rows=[['Tháng',score.month],['Trợ giảng',score.assistant_id],['Trạng thái',score.closed_at?'Đã chốt':'Tạm tính'],...POLICY_SCORES.map(([key,label])=>[label,score[key]]),['Đơn giá',score.hourly_rate],['Hệ số đứng lớp',score.class_factor],['Tiền lên lớp',score.class_pay],['Tiền chữa bài',score.teaching_pay],['Tiền phụ đạo',score.tutoring_pay],['Tiền chấm bài',score.grading_pay],['Tổng (chưa gồm video)',score.total_pay]];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`tro-giang-${score.month}-${score.assistant_id}.csv`;a.click();URL.revokeObjectURL(url)}
 return <section className="space-y-4 rounded-2xl border border-white/15 p-4"><h3 className="font-semibold text-white">Thầy chấm điểm và chốt tháng</h3><p className="text-xs text-slate-400">Để trống để dùng điểm tự tính. Tháng không có phụ đạo cần thầy nhập điểm /25. Điểm quan sát /10 do thầy chấm. Lưu lại sẽ mở tháng đã chốt; mọi thay đổi có nhật ký.</p><div className="grid gap-3 sm:grid-cols-2">{POLICY_SCORES.map(([key,label,max])=><label key={key} className="text-sm text-slate-300">{label} /{max}<input className={cls} type="number" min="0" max={max} step="0.01" placeholder={`Tự tính: ${score[key]??'chưa có'}`} value={scores[key]??''} onChange={e=>setScores({...scores,[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<label className="text-sm text-slate-300">Đơn giá giờ trong tháng<input className={cls} type="number" min="1" step="1" value={rate} onChange={e=>setRate(e.target.value)}/></label></div><label className="block text-sm text-slate-300">Lý do / ghi chú cho lần lưu này<textarea className={cls} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-xl border border-white/20 px-4 py-2 text-white disabled:opacity-50" onClick={()=>save(false)}>Lưu điểm / mở lại tháng</button><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50" onClick={()=>save(true)}>Chốt và công bố</button><button onClick={csv} className="px-4 py-2 text-slate-300">Xuất CSV</button></div></section>;
}
