"use client";

import { useCallback, useEffect, useState } from "react";
import { Award, Check, Filter, Search, ShieldCheck, ShieldX } from "lucide-react";
import { CNC_COMPETENCIES, cncCompetencyStates, fetchCourseCompetencyPermissions, setCompetencyPermission, type CompetencyId, type CompetencyPermission } from "@/services/cnc-competencies";
import type { CncLearningRecord } from "@/services/cnc-learning-records";

type MatrixStudent={id:string;name:string;className:string;records:CncLearningRecord[]};
type FilterId="all"|"waiting"|"approved"|"not-passed";

export default function ClassCompetencyMatrix({courseId,students}:{courseId:number;students:MatrixStudent[]}){
  const[permissions,setPermissions]=useState<CompetencyPermission[]>([]);const[query,setQuery]=useState("");const[filter,setFilter]=useState<FilterId>("all");const[busy,setBusy]=useState("");const[error,setError]=useState("");
  const load=useCallback(()=>fetchCourseCompetencyPermissions(courseId).then(setPermissions).catch(cause=>setError(cause instanceof Error?cause.message:"Không tải được ma trận quyền.")),[courseId]);useEffect(()=>{void load()},[load]);
  function stateOf(student:MatrixStudent,competencyId:CompetencyId){const competency=CNC_COMPETENCIES.find(item=>item.id===competencyId)!;const ownPermissions=permissions.filter(item=>item.student_id===student.id);const state=cncCompetencyStates(student.records,ownPermissions)[competencyId];if(state.revoked)return{key:"revoked",label:"Thu hồi",detail:"Đã bị thu hồi",style:"border-red-400/25 bg-red-500/10 text-red-200"};if(state.approved)return{key:"approved",label:"Đã cấp",detail:state.automatic?"Tự động":"Giáo viên cấp",style:"border-emerald-400/25 bg-emerald-500/10 text-emerald-200"};if(state.eligible&&competency.approvalRequired)return{key:"waiting",label:"Chờ duyệt",detail:"Đã đạt điều kiện",style:"border-amber-400/25 bg-amber-500/10 text-amber-200"};return{key:"not-started",label:"Chưa đạt",detail:competency.permission,style:"border-white/5 bg-white/[.02] text-slate-500"}}
  const visible=students.filter(student=>{const text=`${student.name} ${student.className}`.toLocaleLowerCase("vi-VN");if(!text.includes(query.trim().toLocaleLowerCase("vi-VN")))return false;const states=CNC_COMPETENCIES.map(item=>stateOf(student,item.id).key);return filter==="all"||(filter==="waiting"&&states.includes("waiting"))||(filter==="approved"&&states.includes("approved"))||(filter==="not-passed"&&states.some(key=>key==="failed"||key==="not-started"))});
  const waiting=students.reduce((sum,student)=>sum+CNC_COMPETENCIES.filter(item=>stateOf(student,item.id).key==="waiting").length,0);const approved=students.reduce((sum,student)=>sum+CNC_COMPETENCIES.filter(item=>stateOf(student,item.id).key==="approved").length,0);
  async function update(studentId:string,id:CompetencyId,status:"approved"|"revoked"){const key=`${studentId}-${id}`;setBusy(key);setError("");try{await setCompetencyPermission(courseId,studentId,id,status);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Không cập nhật được quyền.")}finally{setBusy("")}}
  return <section className="rounded-2xl border border-white/10 bg-[#0B1020] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Quản lý toàn lớp</p><h3 className="mt-1 font-display text-2xl font-bold text-white">Ma trận năng lực & cấp quyền</h3><p className="mt-1 text-sm text-slate-500">Bấm trực tiếp vào ô “Chờ duyệt” để cấp quyền, không cần mở hồ sơ riêng.</p></div><div className="flex gap-2"><span className="rounded-xl bg-amber-500/10 px-3 py-2 text-xs font-bold text-amber-200">{waiting} chờ duyệt</span><span className="rounded-xl bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-200">{approved} quyền đã cấp</span></div></div>
  <div className="mt-5 flex flex-wrap gap-2"><label className="flex min-w-64 flex-1 items-center gap-2 rounded-xl border border-white/10 bg-[#080d1d] px-3"><Search size={16} className="text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm sinh viên hoặc lớp…" className="w-full bg-transparent py-3 text-sm text-white outline-none"/></label><div className="flex items-center gap-1 rounded-xl border border-white/10 bg-[#080d1d] p-1"><Filter size={15} className="mx-2 text-slate-500"/>{([["all","Tất cả"],["waiting","Chờ duyệt"],["approved","Đã cấp"],["not-passed","Chưa đạt"]]as[FilterId,string][]).map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`rounded-lg px-3 py-2 text-xs font-bold ${filter===id?"bg-blue-600 text-white":"text-slate-400"}`}>{label}</button>)}</div></div>{error&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
  <div className="mt-5 max-h-[66vh] overflow-auto rounded-xl border border-white/10"><table className="w-full min-w-[980px] border-separate border-spacing-0 text-left"><thead className="sticky top-0 z-20 bg-[#10192a]"><tr><th className="sticky left-0 z-30 min-w-56 border-b border-r border-white/10 bg-[#10192a] p-4 text-xs uppercase text-slate-400">Sinh viên</th>{CNC_COMPETENCIES.map(item=><th key={item.id} className="min-w-44 border-b border-white/10 p-4 text-xs text-slate-300"><Award size={15} className="mb-1 text-violet-300"/>{item.title}</th>)}</tr></thead><tbody>{visible.map(student=><tr key={student.id} className="group"><td className="sticky left-0 z-10 border-b border-r border-white/5 bg-[#0B1020] p-4 group-hover:bg-[#10192a]"><strong className="block text-sm text-white">{student.name}</strong><small className="text-slate-500">{student.className}</small></td>{CNC_COMPETENCIES.map(item=>{const state=stateOf(student,item.id);const cellKey=`${student.id}-${item.id}`;return <td key={item.id} className="border-b border-white/5 p-2"><button disabled={!item.approvalRequired||busy===cellKey||state.key==="failed"||state.key==="not-started"} onClick={()=>state.key==="waiting"?void update(student.id,item.id,"approved"):state.key==="approved"?void update(student.id,item.id,"revoked"):state.key==="revoked"?void update(student.id,item.id,"approved"):undefined} className={`w-full rounded-xl border p-3 text-left transition ${state.style} disabled:cursor-default`}><span className="flex items-center gap-1.5 text-xs font-bold">{state.key==="approved"?<ShieldCheck size={14}/>:state.key==="revoked"?<ShieldX size={14}/>:state.key==="waiting"?<Check size={14}/>:null}{state.label}</span><small className="mt-1 block opacity-70">{state.detail}</small></button></td>})}</tr>)}{!visible.length&&<tr><td colSpan={5} className="p-10 text-center text-sm text-slate-500">Không có sinh viên phù hợp bộ lọc.</td></tr>}</tbody></table></div><p className="mt-3 text-xs text-slate-500">● Vàng: đạt kiểm tra, chờ cấp · ✓ Xanh: đã cấp · Đỏ: chưa đạt/thu hồi · Xám: chưa làm</p></section>
}
