-- Ngân hàng câu hỏi trắc nghiệm/dịch lệnh CNC do giáo viên tự quản lý.
-- Thay thế nội dung hard-code trong services/cnc-lms.ts (CNC_GATE_QUIZ,
-- CNC_LESSON_2_QUIZ, CNC_LESSON_3_QUIZ, CNC_TURN/MILL_COMMAND_TRANSLATION_QUIZ)
-- và bổ sung Bài tập 3 mới (dịch lệnh trả lời ngắn, chấm theo từ khóa) cho Bài 2 & Bài 3.
-- Chạy sau docs/supabase-schema.sql.

create table if not exists public.cnc_quiz_questions (
  id text primary key,
  quiz_key text not null,
  question_type text not null default 'multiple_choice'
    check (question_type in ('multiple_choice', 'short_answer')),
  question text not null,
  options jsonb,               -- multiple_choice: string[] (4 lựa chọn)
  correct_index int,           -- multiple_choice: chỉ số đáp án đúng trong options
  keywords jsonb,               -- short_answer: string[] từ khóa cần có trong câu trả lời
  min_keyword_matches int,      -- short_answer: số từ khóa tối thiểu để coi là đúng (chấm gần đúng)
  explanation text not null default '',
  order_index int not null default 0,
  updated_by uuid references public.profiles (id),
  updated_at timestamptz not null default now(),
  constraint cnc_quiz_questions_mc_shape check (
    question_type <> 'multiple_choice' or (options is not null and correct_index is not null)
  ),
  constraint cnc_quiz_questions_sa_shape check (
    question_type <> 'short_answer' or (keywords is not null and min_keyword_matches is not null)
  )
);

create index if not exists cnc_quiz_questions_quiz_key_idx
  on public.cnc_quiz_questions (quiz_key, order_index);

alter table public.cnc_quiz_questions enable row level security;

-- Học sinh đã đăng nhập đọc được toàn bộ ngân hàng câu hỏi để làm bài.
drop policy if exists "authenticated read cnc quiz questions" on public.cnc_quiz_questions;
create policy "authenticated read cnc quiz questions"
  on public.cnc_quiz_questions for select to authenticated
  using (true);

-- Chỉ giáo viên/quản trị (role = 'admin') được thêm/sửa/xóa câu hỏi.
drop policy if exists "admin manage cnc quiz questions" on public.cnc_quiz_questions;
create policy "admin manage cnc quiz questions"
  on public.cnc_quiz_questions for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- Dữ liệu khởi tạo (idempotent — chạy lại an toàn nhờ ON CONFLICT)
-- ============================================================

-- Ngân hàng câu hỏi hiện có, di trú từ services/cnc-lms.ts
insert into public.cnc_quiz_questions
  (id, quiz_key, question_type, question, options, correct_index, keywords, min_keyword_matches, explanation, order_index)
values
('cnc-gate-1', 'gate', 'multiple_choice', 'Trước khi mở máy CNC, thao tác nào bắt buộc phải kiểm tra đầu tiên?', '["Nguồn điện, khí nén, dầu bôi trơn và trạng thái nút dừng khẩn.","Tốc độ cắt trong chương trình NC.","Màu sắc của phôi sau gia công.","Tên file chương trình trên máy tính cá nhân."]'::jsonb, 0, null, null, 'Nguồn, khí nén, bôi trơn và nút dừng khẩn là các điều kiện an toàn nền tảng trước khi vận hành.', 0),
('cnc-gate-2', 'gate', 'multiple_choice', 'Khi vừa mở máy, vì sao phải đưa máy về chuẩn máy Reference point?', '["Để bộ điều khiển xác lập đúng tọa độ gốc máy trước khi thao tác tiếp.","Để làm nóng phôi trước khi cắt.","Để tự động sửa mọi lỗi trong chương trình NC.","Để tăng tốc độ trục chính lên mức lớn nhất."]'::jsonb, 0, null, null, 'Reference point giúp máy biết vị trí chuẩn của các trục, tránh sai lệch tọa độ khi vận hành.', 1),
('cnc-gate-3', 'gate', 'multiple_choice', 'Khi gá phôi, yêu cầu nào là quan trọng nhất trước khi chạy thử?', '["Phôi được kẹp chắc chắn, đúng vị trí và không cản trở hành trình dao.","Phôi được đặt càng xa mâm cặp càng tốt.","Phôi chưa cần siết chặt vì chỉ đang chạy mô phỏng.","Phôi phải chạm trực tiếp vào mọi dao trong ổ dao."]'::jsonb, 0, null, null, 'Phôi lỏng hoặc đặt sai vị trí có thể gây văng phôi, gãy dao hoặc va chạm máy.', 2),
('cnc-gate-4', 'gate', 'multiple_choice', 'Geometry Offset dùng để làm gì trong quá trình cài đặt dao?', '["Khai báo vị trí/kích thước dao để máy tính đúng đường chạy dao.","Đổi màu hiển thị của chương trình NC.","Lưu tên sinh viên thực hành.","Tự động chọn vật liệu phôi."]'::jsonb, 0, null, null, 'Geometry Offset cho bộ điều khiển biết vị trí thực của mũi dao theo hệ tọa độ máy/phôi.', 3),
('cnc-gate-5', 'gate', 'multiple_choice', 'Work shift hoặc G54 thường được dùng để xác lập điều gì?', '["Gốc tọa độ làm việc của phôi.","Mật khẩu đăng nhập máy.","Tốc độ quạt làm mát trong xưởng.","Số lượng sinh viên trong nhóm."]'::jsonb, 0, null, null, 'G54/Work shift xác định gốc tọa độ gia công trên phôi để chương trình chạy đúng vị trí.', 4),
('cnc-gate-6', 'gate', 'multiple_choice', 'Trước khi cắt thật, sinh viên bắt buộc phải thực hiện bước nào?', '["Mô phỏng, chạy thử không tải hoặc Single Block để kiểm tra va chạm.","Bỏ qua mô phỏng nếu đã từng làm bài tương tự.","Tăng Feed Override lên 100% ngay từ đầu.","Tắt dung dịch làm mát và đứng sát vùng cắt."]'::jsonb, 0, null, null, 'Chạy thử giúp phát hiện sai tọa độ, sai dao, sai chiều chạy hoặc nguy cơ va chạm trước khi cắt thật.', 5),
('cnc-gate-7', 'gate', 'multiple_choice', 'Nếu trong lúc chạy thử thấy dao đi sai hướng hoặc có nguy cơ va chạm, cần làm gì?', '["Dừng máy ngay bằng Stop/Emergency Stop theo tình huống và báo giảng viên.","Đứng quan sát thêm đến khi dao chạm phôi.","Tăng tốc độ chạy dao để chương trình kết thúc nhanh.","Tự ý tháo phôi khi trục chính còn quay."]'::jsonb, 0, null, null, 'Khi có nguy cơ mất an toàn, ưu tiên dừng máy và báo giảng viên, không cố tiếp tục chương trình.', 6),
('cnc-gate-8', 'gate', 'multiple_choice', 'Trong chế độ JOG/HANDLE, nguyên tắc thao tác an toàn là gì?', '["Di chuyển từng bước có kiểm soát, quan sát khoảng cách dao-phôi-mâm cặp.","Giữ nút di chuyển liên tục mà không cần quan sát vùng máy.","Chỉ nhìn màn hình, không cần nhìn vị trí dao thật.","Cho phép nhiều người cùng bấm bảng điều khiển."]'::jsonb, 0, null, null, 'JOG/HANDLE là thao tác tay, nên phải di chuyển chậm, có kiểm soát và luôn quan sát vùng gia công.', 7),
('cnc-gate-9', 'gate', 'multiple_choice', 'Khi tắt máy và kết thúc ca thực hành, việc nào thuộc quy trình bắt buộc?', '["Tắt máy đúng trình tự, vệ sinh công nghiệp và thực hiện 5S.","Để phoi và dụng cụ lại cho nhóm sau tự xử lý.","Tắt nguồn chính khi trục chính vẫn đang quay.","Mang dao và đồ gá ra khỏi xưởng không cần báo giảng viên."]'::jsonb, 0, null, null, 'Kết thúc ca phải đưa máy về trạng thái an toàn, vệ sinh và sắp xếp đúng 5S.', 8),
('cnc-gate-10', 'gate', 'multiple_choice', 'Điều kiện để được lên máy thực tập trong bài vận hành CNC là gì?', '["Hoàn thành checklist và trả lời đúng toàn bộ 10 câu hỏi chốt chặn.","Chỉ cần xem tiêu đề video là đủ.","Chỉ cần có mặt trong xưởng đúng giờ.","Chỉ cần nộp file .NC, không cần kiểm tra an toàn."]'::jsonb, 0, null, null, 'Đây là bài kiểm tra chốt chặn an toàn, nên yêu cầu đúng 10/10 trước khi thực hành trực tiếp.', 9),
('lesson-2-basic-q1', 'lesson-2-exercise-1', 'multiple_choice', 'Trong khối lệnh tổng quát N_ G_ X_ Y_ Z_ M_ S_ F_ T_ ;, ký tự N dùng để khai báo thông tin nào?', '["Lệnh tốc độ trục chính","Số thứ tự câu lệnh","Lệnh chọn dụng cụ cắt","Lệnh bước tiến dao"]'::jsonb, 1, null, null, 'N là số thứ tự của câu lệnh (số block) trong chương trình CNC.', 0),
('lesson-2-basic-q2', 'lesson-2-exercise-1', 'multiple_choice', 'Ký tự nào sau đây biểu thị lệnh bước tiến dao (Feed) trong chương trình tiện CNC?', '["S","T","F","M"]'::jsonb, 2, null, null, 'F là địa chỉ khai báo lượng hoặc tốc độ chạy dao.', 1),
('lesson-2-basic-q3', 'lesson-2-exercise-1', 'multiple_choice', 'Ký tự ; đặt ở cuối mỗi khối lệnh trong chương trình CNC có ý nghĩa gì?', '["Bắt đầu khối lệnh","Khai báo bán kính dao","Ký tự kết thúc câu lệnh","Bỏ qua câu lệnh"]'::jsonb, 2, null, null, 'Dấu chấm phẩy đánh dấu kết thúc một câu lệnh CNC.', 2),
('lesson-2-basic-q4', 'lesson-2-exercise-1', 'multiple_choice', 'Cặp mã lệnh nào được dùng để khai báo đơn vị đo trong hệ tọa độ gia công?', '["G94 và G95","G70 và G71","G17 và G18","G41 và G42"]'::jsonb, 1, null, null, 'Theo hệ lệnh của tài liệu, G70 và G71 dùng để chọn hệ inch và hệ mét.', 3),
('lesson-2-basic-q5', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh G71 dùng để khai báo đơn vị đo theo hệ nào?', '["Hệ inch","Hệ mét","Hệ độ (Degree)","Hệ radian"]'::jsonb, 1, null, null, 'G71 khai báo đơn vị theo hệ mét trong hệ điều khiển được sử dụng ở bài học.', 4),
('lesson-2-basic-q6', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh G95 được ứng dụng trong gia công tiện có ý nghĩa là gì?', '["Chọn lượng chạy dao theo mm/phút","Chọn lượng chạy dao theo mm/vòng","Chọn tốc độ trục chính theo vòng/phút","Khai báo đơn vị đo hệ mét"]'::jsonb, 1, null, null, 'G95 chọn chế độ lượng chạy dao theo mỗi vòng quay của trục chính.', 5),
('lesson-2-basic-q7', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh nào dùng cho chuyển động chạy dao nhanh không cắt gọt?', '["G01","G00","G02","G03"]'::jsonb, 1, null, null, 'G00 dùng để định vị nhanh, không thực hiện cắt gọt.', 6),
('lesson-2-basic-q8', 'lesson-2-exercise-1', 'multiple_choice', 'Trong cấu trúc lệnh G00 X(U)... Z(W)...;, hai ký tự U và W biểu thị tọa độ điểm đến theo giá trị nào?', '["Tọa độ tuyệt đối","Tọa độ tương đối","Tọa độ cực","Bán kính cung tròn"]'::jsonb, 1, null, null, 'U và W biểu thị lượng dịch chuyển tương đối theo trục X và Z.', 7),
('lesson-2-basic-q9', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh G01 thực hiện chức năng gì trong quá trình gia công?', '["Chạy dao nhanh không cắt gọt","Nội suy cung tròn cùng chiều kim đồng hồ","Nội suy theo đường thẳng","Xóa bù trừ bán kính dao"]'::jsonb, 2, null, null, 'G01 thực hiện nội suy tuyến tính với lượng chạy dao F.', 8),
('lesson-2-basic-q10', 'lesson-2-exercise-1', 'multiple_choice', 'Để tiện mặt đầu, tiện trụ thẳng hoặc tiện côn, người ta thường áp dụng lệnh nào?', '["G00","G01","G02","G73"]'::jsonb, 1, null, null, 'Các chuyển động tiện thẳng và tiện côn cơ bản thường dùng nội suy đường thẳng G01.', 9),
('lesson-2-basic-q11', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh G02 có công dụng nào sau đây?', '["Nội suy cung tròn theo cùng chiều kim đồng hồ","Nội suy cung tròn theo ngược chiều kim đồng hồ","Nội suy theo đường thẳng","Chạy dao nhanh"]'::jsonb, 0, null, null, 'G02 là nội suy cung tròn theo chiều kim đồng hồ.', 10),
('lesson-2-basic-q12', 'lesson-2-exercise-1', 'multiple_choice', 'Khi muốn gia công một khối lồi bằng lệnh nội suy cung tròn ngược chiều kim đồng hồ, mã lệnh cần chọn là:', '["G01","G02","G03","G72"]'::jsonb, 2, null, null, 'G03 là nội suy cung tròn ngược chiều kim đồng hồ.', 11),
('lesson-2-basic-q13', 'lesson-2-exercise-1', 'multiple_choice', 'Trong lệnh nội suy cung tròn (G02/G03), ký tự R đại diện cho tham số nào?', '["Tốc độ quay trục chính","Khoảng cách rút dao","Bán kính cung tròn","Lượng dư gia công"]'::jsonb, 2, null, null, 'R khai báo bán kính của cung tròn cần nội suy.', 12),
('lesson-2-basic-q14', 'lesson-2-exercise-1', 'multiple_choice', 'Tham số I và K trong lệnh nội suy cung tròn (G02/G03) là tọa độ tương đối của tâm quay theo hai phương nào?', '["I theo phương Z, K theo phương X","I theo phương X, K theo phương Z","I theo phương Y, K theo phương Z","I và K đều theo phương X"]'::jsonb, 1, null, null, 'Trên mặt phẳng tiện XZ, I là độ lệch tâm theo X và K là độ lệch tâm theo Z.', 13),
('lesson-2-basic-q15', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh nào được sử dụng để xóa chức năng bù trừ bán kính dao?', '["G40","G41","G42","G70"]'::jsonb, 0, null, null, 'G40 hủy chức năng bù bán kính dao.', 14),
('lesson-2-basic-q16', 'lesson-2-exercise-1', 'multiple_choice', 'Để kích hoạt chế độ bù trừ bán kính dao bên phải, ta dùng mã lệnh nào?', '["G40","G41","G42","G73"]'::jsonb, 2, null, null, 'G42 kích hoạt bù bán kính dao bên phải quỹ đạo lập trình.', 15),
('lesson-2-basic-q17', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh G73 trong lập trình tiện CNC có công dụng là gì?', '["Chu trình tiện tinh dọc trục","Chu trình tiện thô dọc trục","Chu trình tiện rãnh","Lệnh chạy dao nhanh"]'::jsonb, 1, null, null, 'Theo cấu trúc chu trình trong tài liệu, G73 là chu trình tiện thô dọc trục.', 16),
('lesson-2-basic-q18', 'lesson-2-exercise-1', 'multiple_choice', 'Trong cấu trúc chu trình G73 P... Q... U2... W...;, tham số U2 và W lần lượt là:', '["Tọa độ điểm bắt đầu và kết thúc","Chiều sâu cắt thô và khoảng cách rút dao","Lượng dư gia công tinh theo phương X và phương Z","Bước tiến dao thô và bước tiến dao tinh"]'::jsonb, 2, null, null, 'U2 và W là lượng dư để lại cho gia công tinh theo phương X và Z.', 17),
('lesson-2-basic-q19', 'lesson-2-exercise-1', 'multiple_choice', 'Mã lệnh được dùng để thực hiện chu trình tiện tinh dọc trục là:', '["G01","G71","G72","G73"]'::jsonb, 2, null, null, 'Theo hệ chu trình trong tài liệu, G72 thực hiện chu trình tiện tinh dọc trục.', 18),
('lesson-2-basic-q20', 'lesson-2-exercise-1', 'multiple_choice', 'Trong các lệnh chu trình gia công (G73, G72), tham số P và Q có ý nghĩa gì?', '["P là tốc độ trục chính, Q là lượng chạy dao","P là số thứ tự câu lệnh bắt đầu, Q là số thứ tự câu lệnh kết thúc biên dạng","P là bán kính dao, Q là lượng dư gia công","P là chiều sâu cắt, Q là khoảng cách lùi dao"]'::jsonb, 1, null, null, 'P và Q xác định số thứ tự block bắt đầu và kết thúc của biên dạng gia công.', 19),
('lesson-3-q1', 'lesson-3-exercise-1', 'multiple_choice', 'Tên chương trình phay CNC tiêu chuẩn trên hệ điều hành Fanuc 21M bắt đầu bằng ký tự nào?', '["Bắt đầu bằng chữ N và theo sau là 4 chữ số.","Bắt đầu bằng chữ G và theo sau là 3 chữ số.","Bắt đầu bằng chữ O và theo sau là 4 chữ số.","Bắt đầu bằng chữ M và theo sau là 2 chữ số."]'::jsonb, 2, null, null, 'Tên chương trình gồm chữ O và bốn chữ số, ví dụ: O1601.', 0),
('lesson-3-q2', 'lesson-3-exercise-1', 'multiple_choice', 'Nguyên công phay CNC cơ bản thường được tiến hành trên mặt phẳng nào và mã lệnh nào dùng để lựa chọn mặt phẳng đó?', '["Mặt phẳng XY (XOY); sử dụng lệnh G17.","Mặt phẳng ZX (XOZ); sử dụng lệnh G18.","Mặt phẳng YZ (YOZ); sử dụng lệnh G19.","Mặt phẳng tự do; sử dụng lệnh G54."]'::jsonb, 0, null, null, 'G17 chọn mặt phẳng làm việc XY (mặt phẳng XOY) sử dụng cho máy phay.', 1),
('lesson-3-q3', 'lesson-3-exercise-1', 'multiple_choice', 'Trong chương trình phay CNC, đơn vị tốc độ tiến dao (Feedrate) thường được lập trình bằng đơn vị nào và mã lệnh nào dùng để thiết lập đơn vị đó?', '["mm/vòng; sử dụng lệnh G95.","mm/phút; sử dụng lệnh G94.","inch/vòng; sử dụng lệnh G97.","m/phút; sử dụng lệnh G96."]'::jsonb, 1, null, null, 'G94 thiết lập lượng chạy dao theo đơn vị mm/phút, đặc trưng trong gia công phay.', 2),
('lesson-3-q4', 'lesson-3-exercise-1', 'multiple_choice', 'Khi muốn lập trình di chuyển dao đến điểm đích được xác định bằng giá trị khoảng cách tuyệt đối so với điểm gốc phôi (W), ta sử dụng mã lệnh nào?', '["G90","G91","G92","G53"]'::jsonb, 0, null, null, 'G90 là lệnh tọa độ tuyệt đối, dao di chuyển đến điểm xác định so với điểm gốc chuẩn.', 3),
('lesson-3-q5', 'lesson-3-exercise-1', 'multiple_choice', 'Trong hệ tọa độ tương đối (G91) trên máy phay CNC, dao di chuyển đến vị trí mới dựa trên cơ sở nào?', '["Khoảng cách so với điểm gốc máy M.","Khoảng cách so với điểm gốc phôi W.","Khoảng cách từ vị trí hiện tại của dao trước khi thực hiện câu lệnh.","Khoảng cách so với điểm chuẩn dao N."]'::jsonb, 2, null, null, 'G91 là hệ tọa độ tương đối, dao tịnh tiến một khoảng so với điểm hiện hành trước đó.', 4),
('lesson-3-q6', 'lesson-3-exercise-1', 'multiple_choice', 'Mã lệnh G00 trên máy phay CNC được định nghĩa là gì?', '["Chạy dao theo đường thẳng với tốc độ tiến dao định sẵn.","Di chuyển dao nhanh không cắt gọt để định vị dụng cụ cắt.","Di chuyển dao tịnh tiến về chuẩn tham chiếu.","Bù trừ bán kính mũi dao cắt."]'::jsonb, 1, null, null, 'G00 là lệnh di chuyển nhanh không cắt gọt, dùng để định vị dao.', 5),
('lesson-3-q7', 'lesson-3-exercise-1', 'multiple_choice', 'Khối lệnh N10 G01 X25 Y-25 F100; trên máy phay CNC có ý nghĩa kỹ thuật gì?', '["Định vị nhanh dao đến điểm tọa độ X25 Y-25.","Nội suy đường thẳng đến điểm X25 Y-25 với tốc độ tiến dao 100 mm/phút.","Nội suy đường thẳng đến điểm X25 Y-25 với tốc độ tiến dao 100 mm/vòng.","Di chuyển dao nội suy cung tròn với lượng tiến dao 100 mm/phút."]'::jsonb, 1, null, null, 'G01 nội suy đường thẳng có cắt gọt; F là tốc độ chạy dao, đơn vị mm/phút khi dùng G94.', 6),
('lesson-3-q8', 'lesson-3-exercise-1', 'multiple_choice', 'Khi sử dụng lệnh nội suy đường thẳng G01 để bo góc hoặc vát góc trên mặt phẳng gia công, tham số nào được dùng để bo tròn một cung có bán kính quy định?', '["Địa chỉ C.","Địa chỉ R.","Địa chỉ I.","Địa chỉ K."]'::jsonb, 1, null, null, 'Khi dùng G01 để bo cung, cấu trúc lệnh nhập thêm địa chỉ R.', 7),
('lesson-3-q9', 'lesson-3-exercise-1', 'multiple_choice', 'Điểm khác biệt quan trọng nhất giữa mã lệnh G02 và G03 khi phay biên dạng cong là gì?', '["G02 nội suy ngược chiều kim đồng hồ, G03 cùng chiều kim đồng hồ.","G02 nội suy cùng chiều kim đồng hồ, G03 ngược chiều kim đồng hồ.","G02 yêu cầu bán kính R, G03 yêu cầu tọa độ tâm I, J.","G02 dùng trên mặt phẳng XY, G03 dùng trên mặt phẳng YZ."]'::jsonb, 1, null, null, 'G02 nội suy cùng chiều kim đồng hồ, còn G03 nội suy ngược chiều kim đồng hồ.', 8),
('lesson-3-q10', 'lesson-3-exercise-1', 'multiple_choice', 'Trong câu lệnh phay cung tròn sử dụng tọa độ tâm tương đối, hai địa chỉ I và J biểu diễn khoảng cách hình học nào?', '["Khoảng cách từ tâm cung tròn đến điểm gốc phôi W.","Khoảng cách từ vị trí bắt đầu của cung tròn đến tâm cung tròn theo hai phương X và Y tương ứng.","Khoảng cách từ tâm cung tròn đến vị trí kết thúc của cung tròn.","Bán kính của cung tròn cần nội suy."]'::jsonb, 1, null, null, 'I và J là tọa độ tương đối của tâm cung tròn so với điểm bắt đầu theo trục X và Y.', 9),
('lesson-3-q11', 'lesson-3-exercise-1', 'multiple_choice', 'Để tránh sai số gia công do đường kính dụng cụ cắt gây ra khi phay biên dạng (Profile), người ta sử dụng các lệnh bù trừ bán kính dao nào?', '["G43 và G44.","G41 và G42.","G54 và G55.","G90 và G91."]'::jsonb, 1, null, null, 'Lệnh bù bán kính để dịch quỹ đạo tâm dao gồm G41 bên trái và G42 bên phải.', 10),
('lesson-3-q12', 'lesson-3-exercise-1', 'multiple_choice', 'Khi dao phay di chuyển ở phía bên trái của đường biên chi tiết theo chiều tiến dao, ta sử dụng lệnh bù bán kính nào?', '["G40","G41","G42","G43"]'::jsonb, 1, null, null, 'G41 bù bán kính dao trái, nghĩa là dao nằm bên trái đường biên theo chiều chuyển động.', 11),
('lesson-3-q13', 'lesson-3-exercise-1', 'multiple_choice', 'Lệnh nào được sử dụng để hủy bỏ hiệu chỉnh bù trừ bán kính dao sau khi đã phay xong biên dạng?', '["G40","G49","G80","G53"]'::jsonb, 0, null, null, 'G40 hủy bỏ hiệu chỉnh bù trừ bán kính dao.', 12),
('lesson-3-q14', 'lesson-3-exercise-1', 'multiple_choice', 'Để hiệu chỉnh bù trừ chiều dài dao theo chiều dương (+), ta sử dụng mã lệnh G nào đi kèm với địa chỉ H?', '["G41 H_","G42 H_","G43 H_","G44 H_"]'::jsonb, 2, null, null, 'G43 hiệu chỉnh chiều dài dao theo chiều dương, kết hợp với số hiệu hiệu chỉnh H.', 13),
('lesson-3-q15', 'lesson-3-exercise-1', 'multiple_choice', 'Lệnh nào được sử dụng để hủy bỏ hiệu chỉnh bù trừ chiều dài dụng cụ cắt?', '["G40","G49","G80","G98"]'::jsonb, 1, null, null, 'G49 hủy bỏ hiệu chỉnh chiều dài dao.', 14),
('lesson-3-q16', 'lesson-3-exercise-1', 'multiple_choice', 'Mã lệnh M06 trong chương trình phay CNC hệ Fanuc 21M có chức năng gì?', '["Quay trục chính cùng chiều kim đồng hồ.","Dừng trục chính không điều kiện.","Thay dụng cụ cắt (thay dao tự động).","Bật dung dịch tưới nguội."]'::jsonb, 2, null, null, 'M06 là chức năng phụ điều khiển thay dao tự động trên máy phay CNC.', 15),
('lesson-3-q17', 'lesson-3-exercise-1', 'multiple_choice', 'Để thiết lập hệ tọa độ gia công (gốc phôi W) trên máy phay CNC, người lập trình có thể lựa chọn 6 hệ tọa độ làm việc chuẩn nào?', '["G50 đến G55","G52 đến G57","G54 đến G59","G90 đến G95"]'::jsonb, 2, null, null, 'Sáu hệ tọa độ làm việc chuẩn được chọn bằng các mã G54 đến G59.', 16),
('lesson-3-q18', 'lesson-3-exercise-1', 'multiple_choice', 'Lệnh G80 trong lập trình phay CNC được dùng để làm gì?', '["Kết thúc và hủy bỏ toàn bộ chu trình gia công lỗ.","Hủy bỏ bù trừ bán kính dụng cụ cắt.","Khởi động chu trình taro ren.","Trả dụng cụ cắt về chuẩn tham chiếu máy."]'::jsonb, 0, null, null, 'G80 hủy bỏ toàn bộ chu trình gia công lỗ đã gọi trước đó.', 17),
('lesson-3-q19', 'lesson-3-exercise-1', 'multiple_choice', 'Trong chu trình khoan lỗ sâu bước G83: G83 G99 G90 G00 X50 Y50 Z-98 I-22 J3 F100; hai tham số I và J được định nghĩa lần lượt là gì?', '["I là bán kính hốc tròn, J là chiều sâu một lớp cắt.","I là giá trị mỗi bước khoan theo phương trục chính, J là số bước khoan thực hiện.","I là lượng dư gia công thô, J là lượng dư gia công tinh.","I là khoảng cách an toàn, J là thời gian dừng ở đáy lỗ."]'::jsonb, 1, null, null, 'Trong chu trình G83 phay Fanuc, I định nghĩa trị số bước khoan và J định nghĩa số lần thực hiện bước khoan.', 18),
('lesson-3-q20', 'lesson-3-exercise-1', 'multiple_choice', 'Khi mô phỏng chương trình phay CNC trên WinNC32 hệ Fanuc 21M, để chạy mô phỏng kiểm tra chương trình (SIMULATION), ta nhấn phím mềm nào?', '["[TOOLS] (F3)","[WORKP] (F4)","[SIMUL] (F6)","[3DVIEW] (F3)"]'::jsonb, 2, null, null, 'Ở chế độ phay WinNC 21M, phím đồ họa SIMUL để chạy mô phỏng là F6.', 19),
('turn-block-q1', 'lesson-2-exercise-2', 'multiple_choice', 'G00 X50 Z2', '["Phay đường thẳng có cắt gọt đến X50 Z2","Chạy dao nhanh (không cắt gọt) đến vị trí X50 Z2","Nội suy cung tròn đến X50 Z2","Tiện ren đến X50 Z2"]'::jsonb, 1, null, null, 'G00 là chuyển động định vị nhanh, không cắt gọt.', 0),
('turn-block-q2', 'lesson-2-exercise-2', 'multiple_choice', 'G01 X30 Z-40 F0.2', '["Tiện thẳng (nội suy tuyến tính) đến X30 Z-40, lượng chạy dao 0.2mm/vòng","Chạy dao nhanh đến X30 Z-40","Nội suy cung tròn đến X30 Z-40, F0.2","Tiện ren bước 0.2mm đến X30 Z-40"]'::jsonb, 0, null, null, 'G01 nội suy tuyến tính đến X30 Z-40 với lượng chạy dao F0.2.', 1),
('turn-block-q3', 'lesson-2-exercise-2', 'multiple_choice', 'G02 X40 Z-20 R10', '["Nội suy cung tròn ngược chiều kim đồng hồ đến X40 Z-20, bán kính 10","Nội suy cung tròn thuận chiều kim đồng hồ đến X40 Z-20, bán kính 10","Tiện côn thẳng đến X40 Z-20, R10","Tiện rãnh tại X40 Z-20, sâu R10"]'::jsonb, 1, null, null, 'G02 nội suy cung tròn thuận chiều kim đồng hồ, R10 là bán kính.', 2),
('turn-block-q4', 'lesson-2-exercise-2', 'multiple_choice', 'G54 G90 G00 X100 Z100', '["Gọi gốc tọa độ máy, hệ tương đối, chạy nhanh về X100 Z100","Gọi gốc tọa độ phôi G54, hệ tọa độ tuyệt đối, chạy nhanh về X100 Z100","Gọi bù dao T01, chạy nhanh về X100 Z100","Gọi gốc tọa độ phôi G55, hệ tương đối, về X100 Z100"]'::jsonb, 1, null, null, 'G54 chọn gốc phôi, G90 chọn tọa độ tuyệt đối và G00 chạy nhanh.', 3),
('turn-block-q5', 'lesson-2-exercise-2', 'multiple_choice', 'T0101', '["Gọi dao số 01 và bù dao (offset) số 01","Gọi chương trình con số 01","Gọi gốc tọa độ phôi số 01","Gọi tốc độ trục chính số 01"]'::jsonb, 0, null, null, 'Hai cặp số lần lượt chỉ số dao và số hiệu offset.', 4),
('turn-block-q6', 'lesson-2-exercise-2', 'multiple_choice', 'G96 S150 M03', '["Tốc độ trục chính không đổi vòng/phút S150, quay ngược chiều kim đồng hồ","Tốc độ cắt không đổi (Constant Surface Speed) 150 m/phút, trục chính quay thuận chiều kim đồng hồ","Tốc độ chạy dao không đổi F150, trục chính dừng","Giới hạn tốc độ trục chính tối đa 150 vòng/phút"]'::jsonb, 1, null, null, 'G96 chọn tốc độ cắt không đổi, S150 đặt 150 m/phút và M03 quay thuận.', 5),
('turn-block-q7', 'lesson-2-exercise-2', 'multiple_choice', 'G97 S1000 M03', '["Tốc độ trục chính không đổi 1000 vòng/phút (constant RPM), quay thuận chiều kim đồng hồ","Tốc độ cắt không đổi 1000 m/phút, quay ngược chiều kim đồng hồ","Giới hạn tốc độ cắt tối đa 1000 m/phút","Chạy dao nhanh với tốc độ trục chính 1000"]'::jsonb, 0, null, null, 'G97 chọn tốc độ vòng quay không đổi, S1000 và M03 quay thuận.', 6),
('turn-block-q8', 'lesson-2-exercise-2', 'multiple_choice', 'G71 U2 R1', '["Chu trình tiện tinh, chiều sâu cắt 2mm, lượng lùi dao 1mm","Chu trình tiện thô dọc trục (Rough Turning Cycle), chiều sâu cắt mỗi lát U2 (2mm/bán kính), lượng lùi dao R1","Chu trình tiện rãnh, chiều sâu 2mm, bán kính đáy rãnh 1mm","Chu trình tiện ren, bước ren 2mm, số lần cắt 1"]'::jsonb, 1, null, null, 'G71 là chu trình tiện thô dọc trục; U và R đặt chiều sâu cắt và lượng lùi.', 7),
('turn-block-q9', 'lesson-2-exercise-2', 'multiple_choice', 'G70 P10 Q20', '["Chu trình tiện thô từ khối lệnh N10 đến N20","Chu trình tiện tinh (Finishing Cycle), thực hiện lại biên dạng từ khối lệnh N10 đến N20","Chu trình khoan lỗ từ N10 đến N20","Chu trình tiện ren từ N10 đến N20"]'::jsonb, 1, null, null, 'G70 tiện tinh lại biên dạng được xác định từ block P đến Q.', 8),
('turn-block-q10', 'lesson-2-exercise-2', 'multiple_choice', 'G28 U0 W0', '["Về gốc tọa độ phôi G54 theo X, Z","Về điểm tham chiếu máy (Machine Zero Point) theo cả hai trục X (U0), Z (W0)","Chạy dao nhanh đến X0 Z0 theo hệ tuyệt đối","Tiện côn về vị trí gốc máy"]'::jsonb, 1, null, null, 'G28 đưa các trục X và Z về điểm tham chiếu máy.', 9),
('turn-block-q11', 'lesson-2-exercise-2', 'multiple_choice', 'G01 X-2 F0.1', '["Tiện mặt đầu (Facing) vào tâm phôi đến đường kính X-2, F0.1","Chạy dao nhanh vào tâm phôi","Tiện ren vào tâm phôi","Tiện rãnh cắt đứt tại X-2"]'::jsonb, 0, null, null, 'G01 chạy dao theo X vào qua tâm để tiện mặt đầu với F0.1.', 10),
('turn-block-q12', 'lesson-2-exercise-2', 'multiple_choice', 'M08 / M09', '["Bật/tắt trục chính (Spindle)","Bật (M08) và tắt (M09) dung dịch làm mát (Coolant)","Bật/tắt chế độ Single Block","Bật/tắt bù bán kính mũi dao"]'::jsonb, 1, null, null, 'M08 bật và M09 tắt dung dịch làm mát.', 11),
('turn-block-q13', 'lesson-2-exercise-2', 'multiple_choice', 'G96 G50 S2000', '["Tốc độ cắt không đổi, giới hạn tốc độ trục chính tối đa (Max Spindle Speed) 2000 vòng/phút","Đặt gốc tọa độ phôi tại S2000","Tốc độ trục chính không đổi 2000 vòng/phút, không giới hạn","Tiện ren với bước 2000"]'::jsonb, 0, null, null, 'G96 dùng tốc độ cắt không đổi và G50 S2000 giới hạn tốc độ trục chính.', 12),
('turn-block-q14', 'lesson-2-exercise-2', 'multiple_choice', 'G32 X30 Z-40 F2.0', '["Tiện thẳng thông thường đến X30 Z-40","Tiện ren (Thread Cutting) đơn giản đến X30 Z-40, bước ren F2.0","Chạy dao nhanh đến X30 Z-40","Chu trình tiện thô đến X30 Z-40"]'::jsonb, 1, null, null, 'G32 cắt ren đến tọa độ đích, F2.0 là bước ren.', 13),
('turn-block-q15', 'lesson-2-exercise-2', 'multiple_choice', 'G04 X2.0', '["Di chuyển dao nhanh đến X2.0","Dừng dao tạm thời (Dwell) trong 2 giây","Tiện rãnh sâu 2.0mm","Dừng chương trình 2 phút"]'::jsonb, 1, null, null, 'G04 là lệnh dừng tạm thời; X2.0 quy định thời gian 2 giây.', 14),
('turn-block-q16', 'lesson-2-exercise-2', 'multiple_choice', 'G01 X50 Z-30 F0.15', '["Tiện côn (taper) đồng thời hai trục X, Z đến điểm (50, -30), F0.15","Chỉ tiện theo Z, bỏ qua X","Chỉ tiện theo X, bỏ qua Z","Nội suy cung tròn đến (50, -30)"]'::jsonb, 0, null, null, 'G01 nội suy đồng thời X và Z tạo đường côn đến điểm đích.', 15),
('turn-block-q17', 'lesson-2-exercise-2', 'multiple_choice', 'G40 G01 X30', '["Kích hoạt bù bán kính mũi dao bên trái (G41)","Hủy bù bán kính mũi dao (Tool Nose Radius Compensation Cancel), tiện thẳng đến X30","Kích hoạt bù bán kính mũi dao bên phải (G42)","Hủy bù chiều dài dao, tiện thẳng đến X30"]'::jsonb, 1, null, null, 'G40 hủy bù bán kính mũi dao, G01 tiếp tục tiện thẳng đến X30.', 16),
('turn-block-q18', 'lesson-2-exercise-2', 'multiple_choice', 'M00 / M01', '["Kết thúc chương trình và quay về đầu (M30)","Dừng trục chính và tắt coolant","Dừng chương trình bắt buộc (M00) hoặc dừng tùy chọn (M01 - Optional Stop)","Gọi chương trình con M00/M01"]'::jsonb, 2, null, null, 'M00 là dừng bắt buộc; M01 dừng khi Optional Stop được bật.', 17),
('turn-block-q19', 'lesson-2-exercise-2', 'multiple_choice', 'G92 X40 Z-30 F2.0', '["Chu trình tiện ren đơn giản (Simple Threading Cycle) đến X40 Z-30, bước ren F2.0","Thiết lập gốc tọa độ phôi tại X40 Z-30","Chu trình tiện thô đến X40 Z-30","Về điểm tham chiếu máy tại X40 Z-30"]'::jsonb, 0, null, null, 'Trong ngữ cảnh tiện Fanuc của đề, G92 là chu trình tiện ren đơn giản với bước F2.0.', 18),
('turn-block-q20', 'lesson-2-exercise-2', 'multiple_choice', 'G50 X100 Z150', '["Chạy dao nhanh đến X100 Z150","Thiết lập/gán giá trị tọa độ hiện tại của dao là X100 Z150 (Coordinate System Setting)","Giới hạn tốc độ trục chính tại X100 Z150","Về điểm tham chiếu máy tại X100 Z150"]'::jsonb, 1, null, null, 'G50 với địa chỉ X/Z gán tọa độ hiện tại cho hệ tọa độ.', 19),
('mill-translate-q1', 'lesson-3-exercise-2', 'multiple_choice', 'G01 X20 Y10 F150', '["Phay đường thẳng (nội suy tuyến tính) đến X20 Y10, tốc độ chạy dao F150","Nội suy cung tròn đến X20 Y10, F150","Chạy dao nhanh (không cắt gọt) đến X20 Y10","Bù chiều dài dao đến X20 Y10"]'::jsonb, 0, null, null, 'G01 là nội suy tuyến tính có cắt gọt; X, Y là tọa độ đích và F150 là tốc độ chạy dao.', 0),
('mill-translate-q2', 'lesson-3-exercise-2', 'multiple_choice', 'G00 X0 Y0 Z50', '["Phay thẳng có cắt gọt đến X0 Y0 Z50","Di chuyển nhanh (không cắt gọt) dao đến vị trí X0 Y0 Z50","Nội suy cung tròn đến X0 Y0 Z50","Dừng chương trình tại X0 Y0 Z50"]'::jsonb, 1, null, null, 'G00 dùng để định vị nhanh, không thực hiện chuyển động cắt gọt.', 1),
('mill-translate-q3', 'lesson-3-exercise-2', 'multiple_choice', 'G03 X40 Y40 R20 F180', '["Nội suy cung tròn thuận chiều kim đồng hồ đến X40 Y40, R20","Phay đường thẳng đến X40 Y40, R20","Nội suy cung tròn ngược chiều kim đồng hồ đến X40 Y40, bán kính 20, F180","Chạy dao nhanh đến X40 Y40, bán kính 20"]'::jsonb, 2, null, null, 'G03 là nội suy cung tròn ngược chiều kim đồng hồ; R20 là bán kính và F180 là tốc độ chạy dao.', 2),
('mill-translate-q4', 'lesson-3-exercise-2', 'multiple_choice', 'G54 G90 G00 X0 Y0', '["Gọi gốc tọa độ máy, hệ tọa độ tương đối, chạy nhanh về X0 Y0","Gọi gốc tọa độ phôi G54, hệ tọa độ tuyệt đối, chạy nhanh về gốc X0 Y0","Gọi bù chiều dài dao H01, chạy nhanh về X0 Y0","Gọi gốc tọa độ phôi G55, hệ tọa độ tương đối, về X0 Y0"]'::jsonb, 1, null, null, 'G54 chọn gốc phôi, G90 chọn tọa độ tuyệt đối và G00 định vị nhanh đến X0 Y0.', 3),
('mill-translate-q5', 'lesson-3-exercise-2', 'multiple_choice', 'G43 H01 Z50', '["Bù bán kính dao theo H01, di chuyển đến Z50","Hủy bù chiều dài dao, di chuyển đến Z50","Bù chiều dài dao theo số hiệu H01, di chuyển dao lên Z50","Gọi gốc tọa độ phôi H01, lên Z50"]'::jsonb, 2, null, null, 'G43 kích hoạt bù chiều dài dao dương, H01 chọn ô hiệu chỉnh chiều dài số 01 và Z50 là vị trí đích.', 4),
('mill-translate-q6', 'lesson-3-exercise-2', 'multiple_choice', 'G91 G01 X10', '["Chuyển sang hệ tọa độ tuyệt đối, di chuyển đến X10","Chuyển sang hệ tọa độ tương đối (incremental), di chuyển thêm 10mm theo X","Chạy dao nhanh thêm 10mm theo X","Nội suy cung tròn thêm 10mm theo X"]'::jsonb, 1, null, null, 'G91 chọn tọa độ tương đối; G01 X10 làm dao nội suy thẳng thêm 10 mm theo chiều dương X.', 5),
('mill-translate-q7', 'lesson-3-exercise-2', 'multiple_choice', 'M03 S1000', '["Trục chính quay ngược chiều kim đồng hồ, tốc độ 1000mm/phút","Bật dung dịch làm mát, tốc độ 1000 vòng/phút","Trục chính quay thuận chiều kim đồng hồ, tốc độ 1000 vòng/phút","Dừng trục chính ở tốc độ 1000 vòng/phút"]'::jsonb, 2, null, null, 'M03 khởi động trục chính theo chiều kim đồng hồ; S1000 đặt tốc độ 1000 vòng/phút.', 6),
('mill-translate-q8', 'lesson-3-exercise-2', 'multiple_choice', 'G00 G90 X30 Y30 Z5', '["Chạy dao cắt gọt (feed) đến X30 Y30 Z5","Chạy dao nhanh, tuyệt đối, đến vị trí X30 Y30 Z5","Nội suy cung tròn đến X30 Y30 Z5","Chạy dao nhanh, tương đối, đến X30 Y30 Z5"]'::jsonb, 1, null, null, 'G00 là chạy nhanh và G90 xác định X30 Y30 Z5 theo hệ tọa độ tuyệt đối.', 7),
('mill-translate-q9', 'lesson-3-exercise-2', 'multiple_choice', 'G02 X60 Y0 I20 J0', '["Nội suy cung tròn dùng bán kính R, không dùng tâm I J","Phay đường thẳng đến X60 Y0, bỏ qua I J","Nội suy cung tròn thuận chiều kim đồng hồ đến X60 Y0, tâm cung cách điểm đầu (I20, J0)","Nội suy cung tròn ngược chiều kim đồng hồ đến X60 Y0, tâm (I20, J0)"]'::jsonb, 2, null, null, 'G02 nội suy cung tròn theo chiều kim đồng hồ; I và J mô tả độ lệch tâm cung so với điểm bắt đầu.', 8),
('mill-translate-q10', 'lesson-3-exercise-2', 'multiple_choice', 'G28 G91 Z0', '["Về gốc phôi G54 theo trục Z","Về điểm tham chiếu máy (Machine Zero Point) theo trục Z, hệ tương đối","Bù chiều dài dao theo trục Z","Chạy dao nhanh tuyệt đối theo trục Z về 0"]'::jsonb, 1, null, null, 'G28 đưa trục về điểm tham chiếu máy; G91 Z0 khai báo điểm trung gian theo hệ tương đối cho trục Z.', 9),
('mill-translate-q11', 'lesson-3-exercise-2', 'multiple_choice', 'G01 Z-5 F80', '["Chạy dao nhanh lên Z-5","Nội suy cung tròn xuống Z-5","Phay ăn dao xuống theo trục Z, sâu -5mm, F80","Dừng dao tạm thời tại Z-5"]'::jsonb, 2, null, null, 'G01 tạo chuyển động ăn dao tuyến tính đến Z-5 với tốc độ chạy dao F80.', 10),
('mill-translate-q12', 'lesson-3-exercise-2', 'multiple_choice', 'M08 / M09', '["Bật/tắt trục chính (Spindle)","Bật (M08) và tắt (M09) dung dịch làm mát (Coolant)","Bật/tắt đèn báo máy","Bật/tắt chế độ Single Block"]'::jsonb, 1, null, null, 'M08 bật và M09 tắt hệ thống dung dịch làm mát.', 11),
('mill-translate-q13', 'lesson-3-exercise-2', 'multiple_choice', 'G17 G02 X20 Y0 R10', '["Chọn mặt phẳng nội suy XZ, cung tròn ngược chiều kim đồng hồ","Chọn mặt phẳng nội suy YZ, cung tròn thuận chiều kim đồng hồ","Chọn mặt phẳng nội suy XY, cung tròn thuận chiều kim đồng hồ đến X20 Y0, R10","Chọn mặt phẳng nội suy XY, phay đường thẳng đến X20 Y0"]'::jsonb, 2, null, null, 'G17 chọn mặt phẳng XY; G02 nội suy cung tròn theo chiều kim đồng hồ đến X20 Y0 với bán kính R10.', 12),
('mill-translate-q14', 'lesson-3-exercise-2', 'multiple_choice', 'G20 / G21', '["Chọn hệ tọa độ tuyệt đối (G20) hoặc tương đối (G21)","Chọn đơn vị đo Inch (G20) hoặc Milimet (G21)","Chọn mặt phẳng nội suy XY (G20) hoặc XZ (G21)","Bật (G20) hoặc tắt (G21) bù bán kính dao"]'::jsonb, 1, null, null, 'G20 thiết lập đơn vị inch, còn G21 thiết lập đơn vị milimét.', 13),
('mill-translate-q15', 'lesson-3-exercise-2', 'multiple_choice', 'T01 M06', '["Gọi Work Offset số 01","Gọi bù chiều dài dao số 01","Gọi dao số 01 và thực hiện lệnh thay dao (Tool Change)","Gọi chương trình con số 01"]'::jsonb, 2, null, null, 'T01 chọn dao số 01 và M06 thực hiện chu trình thay dao.', 14),
('mill-translate-q16', 'lesson-3-exercise-2', 'multiple_choice', 'G04 X2.0', '["Di chuyển dao nhanh đến X2.0","Dừng dao tạm thời (Dwell) trong 2 giây","Phay đường thẳng đến X2.0 trong 2 giây","Dừng chương trình 2 phút"]'::jsonb, 1, null, null, 'G04 là lệnh dừng tạm thời; trong cấu trúc của đề, X2.0 quy định thời gian dừng 2 giây.', 15),
('mill-translate-q17', 'lesson-3-exercise-2', 'multiple_choice', 'G01 X50 Y50 Z-2 F100', '["Chỉ di chuyển theo Z, bỏ qua X và Y","Nội suy cung tròn 3 trục đến (50, 50, -2)","Chạy dao nhanh 3 trục đến (50, 50, -2)","Phay nội suy thẳng đồng thời 3 trục X, Y, Z đến điểm (50, 50, -2), F100"]'::jsonb, 3, null, null, 'G01 nội suy tuyến tính đồng thời các trục được khai báo đến X50 Y50 Z-2 với tốc độ F100.', 16),
('mill-translate-q18', 'lesson-3-exercise-2', 'multiple_choice', 'G40 G01 X30', '["Kích hoạt bù bán kính dao bên trái (G41)","Hủy bù bán kính dao (Cutter Compensation Cancel), phay thẳng đến X30","Kích hoạt bù bán kính dao bên phải (G42)","Hủy bù chiều dài dao, phay thẳng đến X30"]'::jsonb, 1, null, null, 'G40 hủy bù bán kính dao, sau đó G01 thực hiện chuyển động thẳng đến X30.', 17),
('mill-translate-q19', 'lesson-3-exercise-2', 'multiple_choice', 'M00 / M01', '["Kết thúc chương trình và quay về đầu (M30)","Dừng trục chính và tắt coolant","Dừng chương trình bắt buộc (M00) hoặc dừng tùy chọn (M01 - Optional Stop)","Gọi chương trình con M00/M01"]'::jsonb, 2, null, null, 'M00 luôn dừng chương trình; M01 chỉ dừng khi chức năng Optional Stop được bật.', 18),
('mill-translate-q20', 'lesson-3-exercise-2', 'multiple_choice', 'G92 X0 Y0 Z0 (thiết lập G54 tương đương)', '["Về điểm tham chiếu máy (Machine Zero Point)","Thiết lập/gán giá trị tọa độ hiện tại của dao là gốc tọa độ phôi (Work Offset)","Hủy toàn bộ Work Offset đang dùng","Bù chiều dài dao về giá trị 0"]'::jsonb, 1, null, null, 'Trong ngữ cảnh câu hỏi, G92 gán tọa độ vị trí hiện tại thành X0 Y0 Z0 để thiết lập gốc làm việc.', 19)
on conflict (id) do update set
  quiz_key = excluded.quiz_key,
  question_type = excluded.question_type,
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  keywords = excluded.keywords,
  min_keyword_matches = excluded.min_keyword_matches,
  explanation = excluded.explanation,
  order_index = excluded.order_index,
  updated_at = now();

-- Ngân hàng câu hỏi mới: Bài tập 3 (dịch lệnh trả lời ngắn, chấm theo từ khóa)
insert into public.cnc_quiz_questions
  (id, quiz_key, question_type, question, options, correct_index, keywords, min_keyword_matches, explanation, order_index)
values
('turn-short-q1', 'lesson-2-exercise-6', 'short_answer', 'G00 X80 Z5', null, null, '["G00","chạy dao nhanh","không cắt gọt","X80","Z5"]'::jsonb, 3, 'G00 định vị nhanh không cắt gọt đến X80 Z5.', 0),
('turn-short-q2', 'lesson-2-exercise-6', 'short_answer', 'G01 X45 Z-60 F0.15', null, null, '["G01","tiện thẳng","nội suy tuyến tính","X45","Z-60","F0.15"]'::jsonb, 4, 'G01 nội suy tuyến tính đến X45 Z-60, lượng chạy dao F0.15 mm/vòng.', 1),
('turn-short-q3', 'lesson-2-exercise-6', 'short_answer', 'G03 X35 Z-15 R8', null, null, '["G03","nội suy cung tròn","ngược chiều kim đồng hồ","X35","Z-15","R8"]'::jsonb, 4, 'G03 nội suy cung tròn ngược chiều kim đồng hồ, bán kính R8.', 2),
('turn-short-q4', 'lesson-2-exercise-6', 'short_answer', 'G96 S180 M04', null, null, '["G96","tốc độ cắt không đổi","180","M04","ngược chiều kim đồng hồ"]'::jsonb, 3, 'G96 chọn tốc độ cắt không đổi 180 m/phút; M04 quay trục chính ngược chiều kim đồng hồ.', 3),
('turn-short-q5', 'lesson-2-exercise-6', 'short_answer', 'T0303', null, null, '["dao số 03","offset số 03","gọi dao"]'::jsonb, 2, 'T0303 gọi dao số 03 cùng bù dao (offset) số 03.', 4),
('turn-short-q6', 'lesson-2-exercise-6', 'short_answer', 'G71 U1.5 R0.5', null, null, '["G71","tiện thô dọc trục","chiều sâu cắt","1.5","lùi dao","0.5"]'::jsonb, 4, 'G71 chu trình tiện thô dọc trục, chiều sâu cắt mỗi lát 1.5mm, lượng lùi dao 0.5mm.', 5),
('turn-short-q7', 'lesson-2-exercise-6', 'short_answer', 'G70 P20 Q40', null, null, '["G70","tiện tinh","N20","N40","biên dạng"]'::jsonb, 3, 'G70 tiện tinh lại biên dạng từ khối lệnh N20 đến N40.', 6),
('turn-short-q8', 'lesson-2-exercise-6', 'short_answer', 'G28 U0 W0', null, null, '["G28","điểm tham chiếu máy","chuẩn máy","X","Z"]'::jsonb, 3, 'G28 đưa trục X (U0) và Z (W0) về điểm tham chiếu máy.', 7),
('turn-short-q9', 'lesson-2-exercise-6', 'short_answer', 'G32 X25 Z-50 F1.5', null, null, '["G32","tiện ren","bước ren","1.5","X25","Z-50"]'::jsonb, 4, 'G32 tiện ren đến X25 Z-50 với bước ren F1.5.', 8),
('turn-short-q10', 'lesson-2-exercise-6', 'short_answer', 'M03 S900 M08', null, null, '["M03","quay thuận chiều kim đồng hồ","900","M08","dung dịch làm mát","bật"]'::jsonb, 4, 'M03 quay trục chính thuận chiều kim đồng hồ 900 vòng/phút; M08 bật dung dịch làm mát.', 9),
('mill-short-q1', 'lesson-3-exercise-6', 'short_answer', 'G00 X10 Y10 Z20', null, null, '["G00","chạy dao nhanh","không cắt gọt","X10","Y10","Z20"]'::jsonb, 4, 'G00 định vị nhanh không cắt gọt đến X10 Y10 Z20.', 0),
('mill-short-q2', 'lesson-3-exercise-6', 'short_answer', 'G01 X70 Y20 F120', null, null, '["G01","nội suy tuyến tính","phay thẳng","X70","Y20","F120"]'::jsonb, 4, 'G01 phay thẳng đến X70 Y20 với tốc độ chạy dao F120 mm/phút.', 1),
('mill-short-q3', 'lesson-3-exercise-6', 'short_answer', 'G02 X15 Y25 R12 F150', null, null, '["G02","nội suy cung tròn","thuận chiều kim đồng hồ","R12","F150"]'::jsonb, 3, 'G02 nội suy cung tròn thuận chiều kim đồng hồ, bán kính R12, F150.', 2),
('mill-short-q4', 'lesson-3-exercise-6', 'short_answer', 'G55 G90 X0 Y0', null, null, '["G55","gốc tọa độ phôi","tọa độ tuyệt đối","X0","Y0"]'::jsonb, 3, 'G55 chọn gốc phôi thứ hai, G90 tọa độ tuyệt đối, chạy về X0 Y0.', 3),
('mill-short-q5', 'lesson-3-exercise-6', 'short_answer', 'G44 H02 Z30', null, null, '["G44","bù chiều dài dao","âm","H02","Z30"]'::jsonb, 3, 'G44 bù chiều dài dao theo chiều âm, số hiệu H02, di chuyển đến Z30.', 4),
('mill-short-q6', 'lesson-3-exercise-6', 'short_answer', 'M04 S1200', null, null, '["M04","quay ngược chiều kim đồng hồ","1200","vòng/phút"]'::jsonb, 3, 'M04 quay trục chính ngược chiều kim đồng hồ, tốc độ 1200 vòng/phút.', 5),
('mill-short-q7', 'lesson-3-exercise-6', 'short_answer', 'T02 M06', null, null, '["dao số 02","thay dao","M06"]'::jsonb, 2, 'T02 chọn dao số 02, M06 thực hiện thay dao.', 6),
('mill-short-q8', 'lesson-3-exercise-6', 'short_answer', 'G41 D01 G01 X40', null, null, '["G41","bù bán kính dao bên trái","D01","phay thẳng","X40"]'::jsonb, 3, 'G41 kích hoạt bù bán kính dao bên trái theo số hiệu D01, sau đó phay thẳng đến X40.', 7),
('mill-short-q9', 'lesson-3-exercise-6', 'short_answer', 'G81 X20 Y20 Z-10 R2 F100', null, null, '["G81","chu trình khoan lỗ","tiêu chuẩn","Z-10","R2","F100"]'::jsonb, 4, 'G81 là chu trình khoan lỗ tiêu chuẩn, khoan đến Z-10, mặt phẳng lùi dao R2, tốc độ F100.', 8),
('mill-short-q10', 'lesson-3-exercise-6', 'short_answer', 'G17 G03 X30 Y10 R15', null, null, '["G17","mặt phẳng XY","G03","ngược chiều kim đồng hồ","R15"]'::jsonb, 4, 'G17 chọn mặt phẳng XY, G03 nội suy cung tròn ngược chiều kim đồng hồ, bán kính R15.', 9)
on conflict (id) do update set
  quiz_key = excluded.quiz_key,
  question_type = excluded.question_type,
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  keywords = excluded.keywords,
  min_keyword_matches = excluded.min_keyword_matches,
  explanation = excluded.explanation,
  order_index = excluded.order_index,
  updated_at = now();
