-- ============================================================
-- ĐÃ THAY THẾ — đừng chạy file này.
-- Bản nháp cũ tạo public.exam_question_results (topic text) nhưng chưa bao giờ
-- được dùng trong code. Thiết kế chính thức (chủ đề chuẩn hoá + cảnh báo phụ đạo)
-- nằm ở:  docs/supabase-migration-exam-analytics.sql
-- File đó tự DROP bảng cũ rồi dựng lại đúng cấu trúc.
-- ============================================================
