-- Biên bản sinh hoạt chủ nhiệm (SHCN) hàng tuần + công việc gắn cho từng sinh viên,
-- hiển thị trên trang "Lớp chủ nhiệm" của giảng viên và trang sinh viên /lop-hoc/sinh-hoat-chu-nhiem.
--
-- Không đụng tới việc đăng biên bản lên portal.caothang.edu.vn (vẫn làm thủ công ngoài hệ thống) —
-- đây chỉ là bản sao nội dung tuần + checklist việc cần làm, để sinh viên xem và tự đánh dấu đã làm
-- ngay trên thachlab.
--
-- Chạy sau supabase-migration-cttc-homeroom.sql (cần course_offerings, can_manage_course(),
-- course_enrollments). Idempotent.

create table if not exists public.homeroom_meetings (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.course_offerings(id) on delete cascade,
  week_label text not null,
  meeting_date date not null,
  content text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists homeroom_meetings_course_idx
  on public.homeroom_meetings(course_id, meeting_date desc);

alter table public.homeroom_meetings enable row level security;

drop policy if exists "admins manage homeroom meetings" on public.homeroom_meetings;
create policy "admins manage homeroom meetings" on public.homeroom_meetings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "instructors manage assigned homeroom meetings" on public.homeroom_meetings;
create policy "instructors manage assigned homeroom meetings" on public.homeroom_meetings
  for all to authenticated
  using (public.can_manage_course(course_id))
  with check (public.can_manage_course(course_id));

drop policy if exists "students read own homeroom meetings" on public.homeroom_meetings;
create policy "students read own homeroom meetings" on public.homeroom_meetings
  for select to authenticated using (
    public.is_admin() or exists(
      select 1 from public.course_enrollments e
      where e.course_id = homeroom_meetings.course_id and e.student_id = auth.uid() and e.status = 'active'
    )
  );

-- ---------- Công việc trong biên bản ----------
-- student_id null = việc chung cho cả lớp (mỗi sinh viên tự tick riêng ở bảng completions);
-- student_id khác null = việc dặn dò riêng, chỉ sinh viên đó thấy.
create table if not exists public.homeroom_tasks (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.homeroom_meetings(id) on delete cascade,
  course_id bigint not null references public.course_offerings(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists homeroom_tasks_meeting_idx on public.homeroom_tasks(meeting_id);
create index if not exists homeroom_tasks_course_student_idx on public.homeroom_tasks(course_id, student_id);

alter table public.homeroom_tasks enable row level security;

drop policy if exists "admins manage homeroom tasks" on public.homeroom_tasks;
create policy "admins manage homeroom tasks" on public.homeroom_tasks
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "instructors manage assigned homeroom tasks" on public.homeroom_tasks;
create policy "instructors manage assigned homeroom tasks" on public.homeroom_tasks
  for all to authenticated
  using (public.can_manage_course(course_id))
  with check (public.can_manage_course(course_id));

drop policy if exists "students read own homeroom tasks" on public.homeroom_tasks;
create policy "students read own homeroom tasks" on public.homeroom_tasks
  for select to authenticated using (
    public.is_admin()
    or public.can_manage_course(course_id)
    or (
      (student_id is null or student_id = auth.uid())
      and exists(
        select 1 from public.course_enrollments e
        where e.course_id = homeroom_tasks.course_id and e.student_id = auth.uid() and e.status = 'active'
      )
    )
  );

-- ---------- Sinh viên tự tick "đã làm" ----------
create table if not exists public.homeroom_task_completions (
  task_id bigint not null references public.homeroom_tasks(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  done_at timestamptz not null default now(),
  primary key (task_id, student_id)
);

create index if not exists homeroom_task_completions_student_idx
  on public.homeroom_task_completions(student_id);

alter table public.homeroom_task_completions enable row level security;

drop policy if exists "admins manage homeroom task completions" on public.homeroom_task_completions;
create policy "admins manage homeroom task completions" on public.homeroom_task_completions
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "instructors read assigned homeroom task completions" on public.homeroom_task_completions;
create policy "instructors read assigned homeroom task completions" on public.homeroom_task_completions
  for select to authenticated using (
    exists(
      select 1 from public.homeroom_tasks t
      where t.id = homeroom_task_completions.task_id and public.can_manage_course(t.course_id)
    )
  );

drop policy if exists "students manage own homeroom task completions" on public.homeroom_task_completions;
create policy "students manage own homeroom task completions" on public.homeroom_task_completions
  for all to authenticated
  using (student_id = auth.uid())
  with check (
    student_id = auth.uid()
    and exists(
      select 1 from public.homeroom_tasks t
      where t.id = homeroom_task_completions.task_id and (t.student_id is null or t.student_id = auth.uid())
    )
  );
