-- GĐ 2.6 / M4 — Nhắc 1 lần/ngày bằng Web Push.
-- Bảng đăng ký push của học sinh + 2 hàm:
--   upsert_my_push_subscription(...)  : HS (authenticated) đăng ký/đổi giờ nhắc cho thiết bị này.
--   claim_push_reminders_due(...)     : CHỈ service_role (Edge Function send-daily-push) gọi mỗi giờ; trả danh sách
--                                       "cần nhắc giờ này" kèm chủ đề yếu nhất, và đánh dấu last_sent_at NGAY
--                                       (nguyên tử -> chạy trùng lịch cũng không nhắc 2 lần/ngày).
-- Quy tắc nhắc: HS role='student', bật, đúng giờ đã chọn (giờ VN), chưa nhắc hôm nay, CHƯA luyện/làm đề hôm nay
-- (ngày VN; ở giờ nhắc 6–22h ngày VN trùng ngày chuỗi của rank_streak_day nên không cần gọi hàm đó, vốn đòi mùa).
-- Chủ đề yếu nhất: cùng quy tắc docs/mastery-rules.md như get_my_weakest_topics (10 lượt gần nhất/YCCĐ, >=4 lượt,
-- <80%, thấp nhất trước) nhưng tính cho nhiều HS một lượt. Không có chủ đề -> topic_name null (tin chung chung).
-- Chạy ngoài giờ HS làm bài (tạo bảng + hàm, không đụng dữ liệu cũ). Rollback ở cuối file.
begin;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  student_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  remind_hour smallint not null default 19 check (remind_hour between 6 and 22),
  enabled boolean not null default true,
  last_sent_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists push_subscriptions_due_idx on public.push_subscriptions (remind_hour) where enabled;
create index if not exists push_subscriptions_student_idx on public.push_subscriptions (student_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "student reads own push subs" on public.push_subscriptions;
create policy "student reads own push subs" on public.push_subscriptions
  for select to authenticated using (student_id = (select auth.uid()));
drop policy if exists "student updates own push subs" on public.push_subscriptions;
create policy "student updates own push subs" on public.push_subscriptions
  for update to authenticated using (student_id = (select auth.uid())) with check (student_id = (select auth.uid()));
drop policy if exists "student deletes own push subs" on public.push_subscriptions;
create policy "student deletes own push subs" on public.push_subscriptions
  for delete to authenticated using (student_id = (select auth.uid()));
-- Không có policy INSERT: thêm dòng đi qua upsert_my_push_subscription (endpoint unique, cùng thiết bị đổi tài khoản
-- thì dòng được chuyển sang người đăng nhập hiện tại — policy thường không cho UPDATE dòng của người khác).

create or replace function public.upsert_my_push_subscription(
  p_endpoint text, p_p256dh text, p_auth text, p_hour integer default 19
) returns void
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'student') then
    raise exception 'only students';
  end if;
  insert into public.push_subscriptions (student_id, endpoint, p256dh, auth_key, remind_hour, enabled, last_sent_at)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth, least(greatest(coalesce(p_hour, 19), 6), 22), true, null)
  on conflict (endpoint) do update
    set student_id = excluded.student_id, p256dh = excluded.p256dh, auth_key = excluded.auth_key,
        remind_hour = excluded.remind_hour, enabled = true;
end;
$$;
revoke all on function public.upsert_my_push_subscription(text, text, text, integer) from public;
grant execute on function public.upsert_my_push_subscription(text, text, text, integer) to authenticated;

create or replace function public.claim_push_reminders_due(p_now timestamptz default now())
returns table (
  subscription_id bigint,
  student_id uuid,
  endpoint text,
  p256dh text,
  auth_key text,
  topic_name text,
  lesson_id bigint,
  level text
)
language sql
volatile
security definer
set search_path = public
as $$
  with t as (
    select extract(hour from (p_now at time zone 'Asia/Ho_Chi_Minh'))::int as hr,
           (date_trunc('day', p_now at time zone 'Asia/Ho_Chi_Minh')) at time zone 'Asia/Ho_Chi_Minh' as day_start
  ),
  due as (
    update public.push_subscriptions s
       set last_sent_at = p_now
      from t
     where s.enabled
       and s.remind_hour = t.hr
       and (s.last_sent_at is null or s.last_sent_at < t.day_start)
       and exists (select 1 from public.profiles p where p.id = s.student_id and p.role = 'student')
       and not exists (select 1 from public.practice_sessions ps where ps.student_id = s.student_id and ps.created_at >= t.day_start)
       and not exists (select 1 from public.exam_results er where er.student_id = s.student_id and er.created_at >= t.day_start)
    returning s.id, s.student_id, s.endpoint, s.p256dh, s.auth_key
  ),
  attempts as (
    select u.student_id, u.topic_id, u.earned, u.max,
           row_number() over (partition by u.student_id, u.topic_id order by u.created_at desc) as rn
    from (
      select r.student_id, r.topic_id, r.earned, r.max, r.created_at
        from public.exam_question_results r
       where r.topic_id is not null and r.student_id in (select d.student_id from due d)
      union all
      select r.student_id, r.topic_id, r.earned, r.max, r.created_at
        from public.practice_question_results r
       where r.topic_id is not null and r.student_id in (select d.student_id from due d)
    ) u
  ),
  agg as (
    select student_id, topic_id, count(*)::int as n, sum(earned) as se, sum(max) as sm
      from attempts where rn <= 10 group by student_id, topic_id
  ),
  worst as (
    select distinct on (a.student_id)
           a.student_id, qt.name as topic_name, qt.lesson_id,
           case when a.se / a.sm >= 0.5 then 'practicing' else 'weak' end as level
      from agg a
      join public.question_topics qt on qt.id = a.topic_id and qt.parent_id is not null
     where a.n >= 4 and a.sm > 0 and a.se / a.sm < 0.8
     order by a.student_id, a.se / a.sm asc, a.n desc, qt.id
  )
  select d.id, d.student_id, d.endpoint, d.p256dh, d.auth_key, w.topic_name, w.lesson_id, w.level
    from due d left join worst w on w.student_id = d.student_id;
$$;
revoke all on function public.claim_push_reminders_due(timestamptz) from public, anon, authenticated;
grant execute on function public.claim_push_reminders_due(timestamptz) to service_role;

commit;

-- ROLLBACK (cũng ở perf/rollback/20261005160000_push_subscriptions.down.sql):
-- drop function if exists public.claim_push_reminders_due(timestamptz);
-- drop function if exists public.upsert_my_push_subscription(text, text, text, integer);
-- drop table if exists public.push_subscriptions;
