-- Sổ học phí theo tháng cho khoá THPT. Không cổng thanh toán, không đổi
-- thpt_registrations.payment_status (ô "Đã đóng" hiện tại giữ nguyên).
--
-- Ẩn mặc định: staff_visible = false, family_visible = false.
-- Mọi hàm ghi từ chối khi staff_visible còn false, kể cả admin gọi RPC.
-- Cách duy nhất để giáo viên thấy sổ là SQL (không có nút, không có menu):
--   update public.thpt_fee_settings set staff_visible = true, updated_at = now() where id;
-- rồi mở /quan-tri/hoc-phi (đường dẫn không nằm trong menu quản trị).
-- Trong trang đó admin mới bật được family_visible — lúc đó phụ huynh thấy
-- từng tháng trên thẻ Học phí. Học sinh không bao giờ thấy sổ này.
--
-- Một học sinh + một mức thu + một tháng = một khoản. Lớp 2 buổi (pair) chỉ
-- một khoản, không thu đúp buổi A và buổi B. Khoá billing_key phải khớp
-- billingKeyOf trong features/tuition/ledger.ts (kiểm bằng scripts/test-tuition-ledger.mts).
--
-- Chạy bất kỳ lúc nào: chỉ thêm bảng và hàm. Rollback ở cuối file và
-- perf/rollback/20261006120000_thpt_fee_ledger.down.sql.
begin;

create table if not exists public.thpt_fee_settings (
  id boolean primary key default true check (id),
  staff_visible boolean not null default false,
  family_visible boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into public.thpt_fee_settings (id, staff_visible, family_visible)
values (true, false, false)
on conflict (id) do nothing;

create table if not exists public.thpt_fee_plans (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes (id) on delete cascade,
  billing_key text not null check (char_length(billing_key) between 1 and 120),
  label text not null check (char_length(label) between 1 and 80),
  amount_vnd integer not null check (amount_vnd between 1 and 20000000),
  due_day smallint not null default 5 check (due_day between 1 and 28),
  active boolean not null default true,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  unique (class_id, billing_key)
);

create table if not exists public.thpt_fee_charges (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.thpt_fee_plans (id) on delete cascade,
  student_id uuid not null references public.profiles (id) on delete cascade,
  period date not null,
  amount_vnd integer not null check (amount_vnd between 1 and 20000000),
  waived boolean not null default false,
  created_at timestamptz not null default now(),
  unique (plan_id, student_id, period),
  check (extract(day from period) = 1)
);
create index if not exists thpt_fee_charges_student_period_idx
  on public.thpt_fee_charges (student_id, period);

create table if not exists public.thpt_fee_payments (
  id bigint generated by default as identity primary key,
  charge_id bigint not null references public.thpt_fee_charges (id) on delete cascade,
  amount_vnd integer not null check (amount_vnd between 1 and 20000000),
  method text not null check (method in ('center', 'transfer')),
  paid_on date not null,
  note text not null default '' check (char_length(note) <= 300),
  recorded_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);
create index if not exists thpt_fee_payments_charge_idx on public.thpt_fee_payments (charge_id);

alter table public.thpt_fee_settings enable row level security;
alter table public.thpt_fee_plans enable row level security;
alter table public.thpt_fee_charges enable row level security;
alter table public.thpt_fee_payments enable row level security;
-- Không policy: anon/authenticated không đọc được bảng. Mọi lối vào là hàm security definer.

-- BEGIN billing_key
create or replace function public.thpt_fee_billing_key(
  p_course_id bigint, p_name text, p_pair_key text, p_pair_slot text
) returns text
language sql immutable
as $$
  select case
    when slot is null or slot = '' then 'course:' || p_course_id::text
    else 'pair:' || coalesce(nullif(btrim(coalesce(p_pair_key, '')), ''), nullif(btrim(head), ''), btrim(coalesce(p_name, '')))
  end
  from (
    select
      upper(coalesce(
        nullif(btrim(coalesce(p_pair_slot, '')), ''),
        substring(coalesce(p_name, '') from '(?i)buổi[[:space:]]+([A-Za-z])')
      )) as slot,
      regexp_replace(coalesce(p_name, ''), '\s+[—–-]\s+.*$', '') as head
  ) s;
$$;
-- END billing_key

create or replace function public.thpt_fee_is_clerk()
returns boolean
language sql stable security definer set search_path = public
as $$
  select public.is_admin()
    or exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid())
        and p.role = 'instructor'
        and p.admin_area = 'thpt'
    );
$$;

create or replace function public.thpt_fee_assert_open(p_class bigint)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if (select auth.uid()) is null then raise exception 'Chưa đăng nhập.'; end if;
  if not public.thpt_fee_is_clerk() then raise exception 'Không có quyền.'; end if;
  if not exists (select 1 from public.thpt_fee_settings s where s.id and s.staff_visible) then
    raise exception 'Sổ học phí đang ẩn.';
  end if;
  if p_class is not null and not public.manages_class(p_class) then
    raise exception 'Không có quyền với lớp này.';
  end if;
end;
$$;

create or replace function public.thpt_fee_visibility()
returns table (staff_visible boolean, family_visible boolean)
language plpgsql stable security definer set search_path = public
as $$
begin
  if not public.thpt_fee_is_clerk() then
    staff_visible := false;
    family_visible := false;
    return next;
    return;
  end if;
  return query
    select s.staff_visible, s.family_visible
    from public.thpt_fee_settings s
    where s.id;
  if not found then
    staff_visible := false;
    family_visible := false;
    return next;
  end if;
end;
$$;

-- Không bật được staff_visible qua hàm này. Cờ đó chỉ đổi bằng SQL ở đầu file.
create or replace function public.thpt_fee_set_visibility(p_staff boolean, p_family boolean)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Không có quyền.'; end if;
  if not exists (select 1 from public.thpt_fee_settings s where s.id and s.staff_visible) then
    raise exception 'Sổ học phí đang ẩn.';
  end if;
  update public.thpt_fee_settings
     set staff_visible = p_staff, family_visible = p_family, updated_at = now()
   where id;
end;
$$;

create or replace function public.thpt_fee_plans(p_class bigint)
returns table (
  id bigint, class_id bigint, billing_key text, label text,
  amount_vnd integer, due_day smallint, active boolean
)
language plpgsql stable security definer set search_path = public
as $$
begin
  perform public.thpt_fee_assert_open(p_class);
  return query
    select p.id, p.class_id, p.billing_key, p.label, p.amount_vnd, p.due_day, p.active
    from public.thpt_fee_plans p
    where p.class_id = p_class
    order by p.label;
end;
$$;

create or replace function public.thpt_fee_upsert_plan(
  p_class bigint, p_billing_key text, p_label text, p_amount integer, p_due_day smallint
) returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  v_id bigint;
  v_label text := btrim(p_label);
begin
  perform public.thpt_fee_assert_open(p_class);
  if v_label is null or char_length(v_label) < 1 or char_length(v_label) > 80 then
    raise exception 'Tên mức thu không hợp lệ.';
  end if;
  if p_amount is null or p_amount < 1 or p_amount > 20000000 then
    raise exception 'Số tiền không hợp lệ.';
  end if;
  if p_due_day is null or p_due_day < 1 or p_due_day > 28 then
    raise exception 'Ngày hạn không hợp lệ.';
  end if;
  if not exists (
    select 1 from public.thpt_courses c
    where c.class_id = p_class
      and public.thpt_fee_billing_key(c.id, c.name, c.pair_key, c.pair_slot) = p_billing_key
  ) then
    raise exception 'Không khớp lớp nào.';
  end if;
  insert into public.thpt_fee_plans (class_id, billing_key, label, amount_vnd, due_day, active, created_by)
  values (p_class, p_billing_key, v_label, p_amount, p_due_day, true, auth.uid())
  on conflict (class_id, billing_key) do update
    set label = excluded.label, amount_vnd = excluded.amount_vnd, due_day = excluded.due_day, active = true
  returning thpt_fee_plans.id into v_id;
  return v_id;
end;
$$;

create or replace function public.thpt_fee_archive_plan(p_plan bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_class bigint;
begin
  select class_id into v_class from public.thpt_fee_plans where id = p_plan;
  if v_class is null then raise exception 'Không thấy mức thu.'; end if;
  perform public.thpt_fee_assert_open(v_class);
  update public.thpt_fee_plans set active = false where id = p_plan;
end;
$$;

create or replace function public.thpt_fee_ensure_month(p_class bigint, p_period date)
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  v_period date := date_trunc('month', p_period)::date;
  v_n integer;
begin
  perform public.thpt_fee_assert_open(p_class);
  if v_period < date '2024-01-01'
     or v_period > (date_trunc('month', (now() at time zone 'Asia/Ho_Chi_Minh'))::date + interval '1 month') then
    raise exception 'Tháng không hợp lệ.';
  end if;
  with ins as (
    insert into public.thpt_fee_charges (plan_id, student_id, period, amount_vnd)
    select distinct on (p.id, r.student_id)
           p.id, r.student_id, v_period, p.amount_vnd
      from public.thpt_fee_plans p
      join public.thpt_courses c on c.class_id = p.class_id
      join public.thpt_registrations r on r.course_id = c.id
     where p.class_id = p_class
       and p.active
       and p.billing_key = public.thpt_fee_billing_key(c.id, c.name, c.pair_key, c.pair_slot)
       and r.student_id is not null
       and r.status in ('active', 'catchup')
     order by p.id, r.student_id, r.id
    on conflict (plan_id, student_id, period) do nothing
    returning 1
  )
  select count(*)::int into v_n from ins;
  return v_n;
end;
$$;

create or replace function public.thpt_fee_ledger(p_class bigint, p_period date)
returns table (
  charge_id bigint, plan_id bigint, student_id uuid, student_name text,
  billing_key text, label text, period date, amount_vnd integer,
  paid_vnd integer, waived boolean, due_day smallint
)
language plpgsql stable security definer set search_path = public
as $$
declare
  v_period date := date_trunc('month', p_period)::date;
begin
  perform public.thpt_fee_assert_open(p_class);
  return query
    select c.id, c.plan_id, c.student_id, coalesce(pr.full_name, 'Học sinh'),
           p.billing_key, p.label, c.period, c.amount_vnd,
           coalesce(sum(pay.amount_vnd), 0)::int, c.waived, p.due_day
      from public.thpt_fee_charges c
      join public.thpt_fee_plans p on p.id = c.plan_id
      join public.profiles pr on pr.id = c.student_id
      left join public.thpt_fee_payments pay on pay.charge_id = c.id
     where p.class_id = p_class and c.period = v_period
     group by c.id, p.billing_key, p.label, p.due_day, pr.full_name
     order by pr.full_name, p.label;
end;
$$;

create or replace function public.thpt_fee_record_payment(
  p_charge bigint, p_amount integer, p_method text, p_paid_on date, p_note text
) returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_class bigint;
  v_note text := btrim(coalesce(p_note, ''));
begin
  select p.class_id into v_class
    from public.thpt_fee_charges c
    join public.thpt_fee_plans p on p.id = c.plan_id
   where c.id = p_charge;
  if v_class is null then raise exception 'Không thấy khoản thu.'; end if;
  perform public.thpt_fee_assert_open(v_class);
  if p_amount is null or p_amount < 1 or p_amount > 20000000 then
    raise exception 'Số tiền không hợp lệ.';
  end if;
  if p_method not in ('center', 'transfer') then
    raise exception 'Hình thức không hợp lệ.';
  end if;
  if p_paid_on < date '2024-01-01'
     or p_paid_on > (now() at time zone 'Asia/Ho_Chi_Minh')::date + 1 then
    raise exception 'Ngày không hợp lệ.';
  end if;
  if char_length(v_note) > 300 then raise exception 'Ghi chú quá dài.'; end if;
  insert into public.thpt_fee_payments (charge_id, amount_vnd, method, paid_on, note, recorded_by)
  values (p_charge, p_amount, p_method, p_paid_on, v_note, auth.uid());
end;
$$;

create or replace function public.thpt_fee_waive(p_charge bigint, p_waived boolean)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_class bigint;
begin
  select p.class_id into v_class
    from public.thpt_fee_charges c
    join public.thpt_fee_plans p on p.id = c.plan_id
   where c.id = p_charge;
  if v_class is null then raise exception 'Không thấy khoản thu.'; end if;
  perform public.thpt_fee_assert_open(v_class);
  update public.thpt_fee_charges set waived = p_waived where id = p_charge;
end;
$$;

-- Phụ huynh đọc khoản của con. family_visible = false → bảng rỗng, không báo lỗi,
-- để thẻ Học phí trên /phu-huynh giữ nguyên như khi chưa có sổ.
create or replace function public.thpt_fee_family_lines()
returns table (
  student_id uuid, student_name text, billing_key text, label text,
  period date, amount_vnd integer, paid_vnd integer, waived boolean, due_day smallint
)
language plpgsql stable security definer set search_path = public
as $$
begin
  if (select auth.uid()) is null then return; end if;
  if not exists (select 1 from public.thpt_fee_settings s where s.id and s.family_visible) then
    return;
  end if;
  return query
    select c.student_id, coalesce(pr.full_name, ''), p.billing_key, p.label,
           c.period, c.amount_vnd, coalesce(sum(pay.amount_vnd), 0)::int, c.waived, p.due_day
      from public.thpt_fee_charges c
      join public.thpt_fee_plans p on p.id = c.plan_id
      join public.profiles pr on pr.id = c.student_id
      left join public.thpt_fee_payments pay on pay.charge_id = c.id
     where public.is_parent_of(c.student_id)
       and c.period >= (date_trunc('month', (now() at time zone 'Asia/Ho_Chi_Minh'))::date - interval '5 months')
       and c.period <= date_trunc('month', (now() at time zone 'Asia/Ho_Chi_Minh'))::date
     group by c.id, c.student_id, pr.full_name, p.billing_key, p.label, p.due_day
     order by c.period desc, p.label;
end;
$$;

revoke all on function public.thpt_fee_billing_key(bigint, text, text, text) from public, anon, authenticated;
revoke all on function public.thpt_fee_is_clerk() from public, anon, authenticated;
revoke all on function public.thpt_fee_assert_open(bigint) from public, anon, authenticated;

revoke all on function public.thpt_fee_visibility() from public;
grant execute on function public.thpt_fee_visibility() to authenticated;
revoke all on function public.thpt_fee_set_visibility(boolean, boolean) from public;
grant execute on function public.thpt_fee_set_visibility(boolean, boolean) to authenticated;
revoke all on function public.thpt_fee_plans(bigint) from public;
grant execute on function public.thpt_fee_plans(bigint) to authenticated;
revoke all on function public.thpt_fee_upsert_plan(bigint, text, text, integer, smallint) from public;
grant execute on function public.thpt_fee_upsert_plan(bigint, text, text, integer, smallint) to authenticated;
revoke all on function public.thpt_fee_archive_plan(bigint) from public;
grant execute on function public.thpt_fee_archive_plan(bigint) to authenticated;
revoke all on function public.thpt_fee_ensure_month(bigint, date) from public;
grant execute on function public.thpt_fee_ensure_month(bigint, date) to authenticated;
revoke all on function public.thpt_fee_ledger(bigint, date) from public;
grant execute on function public.thpt_fee_ledger(bigint, date) to authenticated;
revoke all on function public.thpt_fee_record_payment(bigint, integer, text, date, text) from public;
grant execute on function public.thpt_fee_record_payment(bigint, integer, text, date, text) to authenticated;
revoke all on function public.thpt_fee_waive(bigint, boolean) from public;
grant execute on function public.thpt_fee_waive(bigint, boolean) to authenticated;
revoke all on function public.thpt_fee_family_lines() from public;
grant execute on function public.thpt_fee_family_lines() to authenticated;

revoke all on function public.thpt_fee_visibility() from anon;
revoke all on function public.thpt_fee_set_visibility(boolean, boolean) from anon;
revoke all on function public.thpt_fee_plans(bigint) from anon;
revoke all on function public.thpt_fee_upsert_plan(bigint, text, text, integer, smallint) from anon;
revoke all on function public.thpt_fee_archive_plan(bigint) from anon;
revoke all on function public.thpt_fee_ensure_month(bigint, date) from anon;
revoke all on function public.thpt_fee_ledger(bigint, date) from anon;
revoke all on function public.thpt_fee_record_payment(bigint, integer, text, date, text) from anon;
revoke all on function public.thpt_fee_waive(bigint, boolean) from anon;
revoke all on function public.thpt_fee_family_lines() from anon;

commit;

-- ROLLBACK (cũng ở perf/rollback/20261006120000_thpt_fee_ledger.down.sql):
-- drop function if exists public.thpt_fee_family_lines();
-- drop function if exists public.thpt_fee_waive(bigint, boolean);
-- drop function if exists public.thpt_fee_record_payment(bigint, integer, text, date, text);
-- drop function if exists public.thpt_fee_ledger(bigint, date);
-- drop function if exists public.thpt_fee_ensure_month(bigint, date);
-- drop function if exists public.thpt_fee_archive_plan(bigint);
-- drop function if exists public.thpt_fee_upsert_plan(bigint, text, text, integer, smallint);
-- drop function if exists public.thpt_fee_plans(bigint);
-- drop function if exists public.thpt_fee_set_visibility(boolean, boolean);
-- drop function if exists public.thpt_fee_visibility();
-- drop function if exists public.thpt_fee_assert_open(bigint);
-- drop function if exists public.thpt_fee_is_clerk();
-- drop function if exists public.thpt_fee_billing_key(bigint, text, text, text);
-- drop table if exists public.thpt_fee_payments;
-- drop table if exists public.thpt_fee_charges;
-- drop table if exists public.thpt_fee_plans;
-- drop table if exists public.thpt_fee_settings;
